microsoft/cppwinrt

- 10.0.14393.0/Samples/AsyncReader/pch.h
- 10.0.14393.0/Samples/Blocks/pch.h
- 10.0.14393.0/Samples/JustCoroutines/pch.h
- 10.0.14393.0/Samples/Ocr/pch.h
- 10.0.14393.0/Samples/Syndication/pch.h
- 10.0.14393.0/Samples/Video/pch.h
- 10.0.14393.0/Samples/XamlCode/pch.h
I was an MVP for Direct3D for 10 years, you might already have a CLA on file for me...
> Use / for include paths, not \

- nuget/Microsoft.Windows.CppWinRT.nuspec
> updated nuget project url

- nuget/Microsoft.Windows.CppWinRT.targets
A DependsOnTargets entry was left that is undefined.
> Remove undefined target.

- strings/base_meta.h
> Remove unused internal declaration

- strings/base_std_hash.h
> Specialize std::hash for winrt::guid

- build_test_all.cmd
Build the NuGetTest solution as part of build_test_all.cmd.
TODO:
> Add NuGetTest.sln to build_test_all.cmd

- strings/base_string.h
- test/test/hstring_empty.cpp
- test/test/test.vcxproj
> Fix regression in hstring c_str

- build_test_all.cmd
Existing location downloads a very old nuget.exe.
> Update nuget.exe url to point to the right location.

- cppwinrt/code_writers.h
Created an issue to turn these into scope guards. #516
Completing this to unblock testing.
> Fix async for testwinrt

- vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
- vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
- vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
- vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj
Add ARM64 support to the Universal templates.
> Add ARM64 support to the Universal templates.

- strings/base_collections_map.h
- test/old_tests/UnitTests/range_for.cpp
> Structured binding support for IKeyValuePair

- strings/base_array.h
- test/old_tests/UnitTests/array.cpp
> Allow conversion and comparison of cv-qualified array_view

- cppwinrt/code_writers.h
> Added debugging GUID comment generation

- strings/base_agile_ref.h
- strings/base_weak_ref.h
> add [[nodiscard]] to weak_ref agile_ref get() methods to avoid incorrect use

- nuget/Microsoft.Windows.CppWinRT.props
> Fix authoring error with non-default value for the CppWinRTEnableDefaultPrivateFalse property.

- nuget/Microsoft.Windows.CppWinRT.targets
> Only use Hash task on VS 2019 and higher.

- cppwinrt/main.cpp
> Use correct default output folder

- strings/base_types.h
Fixes #921 - thanks for spotting these @dmachaj - we already inlined most of the heavy hitters but these ones didn't get noticed.
> Inline internal error codes

- cppwinrt/cppwinrt.vcxproj
- cppwinrt/packages.config
- natvis/cppwinrtvisualizer.vcxproj
- natvis/packages.config
Pick up the latest WinMD Nuget (https://github.com/microsoft/winmd/releases/tag/1.0.210505.3)
> Ingest updated Microsoft.Windows.WinMD to fix bug around "-exclude"

- cppwinrt/cppwinrt.vcxproj
- cppwinrt/packages.config
- natvis/cppwinrtvisualizer.vcxproj
- natvis/packages.config
Pick up https://github.com/microsoft/winmd/pull/23 from the winmd library.
> Ingest updated winmd library to fix include/exclude regression

- cppwinrt.props
- cppwinrt/code_writers.h
- test/old_tests/UnitTests/event_consume.cpp
> Ignore errors during manual unregistration

- cppwinrt/main.cpp
> More reliable verbose path output

- cppwinrt/main.cpp
> Document syntax to disable PCH

- nuget/Microsoft.Windows.CppWinRT.targets
> Set -pch correctly from targets when not using PCH

- nuget/Microsoft.Windows.CppWinRT.targets
> Do not delete (clean) a file not written by this target

- .pipelines/sync-mirror.yml
Fixing pool for sync mirror pipeline
> Fixing pool for sync mirror pipeline

- .config/1espt/PipelineAutobaseliningConfig.yml
Cherry-pick auto-generated baseline from internal pipeline
> Merlinbot baseline
