microsoft/cppwinrt

Docs/Migrating C++ CX source code to C++ WinRT.md

More typo fixes.
One thing that was not typo, but I was not sure whether it is right or not:
This C++/CX code:
void LogWrapLine(Platform::String^ str)
converts to the standard C++ code:
void LogWrapLine(std::wstring str)
Do you really recommend to pass c++ wstring by value and not as "const std::wstring& str"? Compiler will figure out to create hstring_ref, doesn't it?

More typo fixes for "Migrating C++ CX source code to C++ WinRT.md"

---

cppwinrt/component_writers.h
test/test_component/Simple.h
test/test_component/test_component.idl

Return value for static events was declared as event_token in the header (when built as a component), but as auto in the implementation.
Align implementation with header.
This fixes #364

Fix implementation of static events

---

build_projection.cmd
cppwinrt.props
run_tests.cmd

Running `build_projection.cmd` is a routine part of C++/WinRT development and this makes for a more convenient inner loop as it avoids command line tab completion to the build folder.

Add prefix to build folder to avoid incorrect tab completion

---

strings/base_array.h

https://github.com/microsoft/xlang/pull/611 broke Clang support as it insists on evaluating the function in all cases since it is not generic.

Restore basic Clang support

---

nuget/Microsoft.Windows.CppWinRT.targets

This PR updates the Make* targets to use a marker file as we can't incrementally build the Make* targets. When we define a relation between inputs and outputs, MSBuild will only pass the inputs that have changed which can cause missing references.
Fixes #386

Update make targets to use marker file as output.

---

nuget/Microsoft.Windows.CppWinRT.targets

The CppWinRTAddXamlReferences/CppWinRTSetXamlLocalAssembly targets should only execute if the xaml language is CppWinRT.
Currently this also affects CX projects and since the winmd files are not yet available by the time this target runs, it causes non-determinism for subsequent builds when files do exist.

The CppWinRTAddXamlReferences/CppWinRTSetXamlLocalAssembly targets should only execute if the xaml language is CppWinRT.

---

nuget/Microsoft.Windows.CppWinRT.targets

Only build the reference projection when there are references.
Fixes #391

Only build the reference projection when there are references.

---

nuget/Microsoft.Windows.CppWinRT.targets

Currently the targets file uses a mix of 2 and 4 space indents. This change makes it 4 spaces throughout the file to make it consistent with the props file.

Format the targets file.

---

vsix/ItemTemplates/ViewModel/ViewModel.cpp
vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/ConsoleApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Desktop/WindowsApplication/WindowsApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/pch.h

Using code from the Windows.UI.Xaml namespace in a viewmodel is considered bad form as the goal of MVVM is to separate view from viewmodel (Windows.UI.Xaml.Data being the exception as the PropertyChanged classes live there). Furthermore, the default templates don't require any classes from that namespace. This makes the code simpler and doesn't by default include the massive Xaml namespace which significantly increases the pch.
Also defines WIN32_LEAN_AND_MEAN;WINRT_LEAN_AND_MEAN; to reduce unnecessary headers from Windows and WinRT.

Remove unnecessary xaml and windows includes.

---

nuget/CppWinrtRules.Project.xml
nuget/Microsoft.Windows.CppWinRT.targets
nuget/readme.md
test/nuget/TestRuntimeComponent1/TestRuntimeComponent1.vcxproj
test/nuget/TestRuntimeComponent2/TestRuntimeComponent2.vcxproj
test/nuget/TestRuntimeComponent3/TestRuntimeComponent3.vcxproj
test/nuget/TestRuntimeComponentEmpty/TestRuntimeComponentEmpty.vcxproj
vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/ConsoleApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Desktop/WindowsApplication/WindowsApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

This PR adds the CppWinRTGenerateWindowsMetadata property to more quickly determine if a project outputs a winmd. This allows a project to determine this without evaluating all its project references for the presence of static libraries.
Tested NuGetTest.sln as well as various razzle projects.
Fixes #399

Add CppWinRTGenerateWindowsMetadata property to more quickly determine if a project outputs a winmd.

---

nuget/Microsoft.Windows.CppWinRT.props
nuget/Microsoft.Windows.CppWinRT.targets

Currently CppWinRT_IncludePath points to the includes in the installed Windows SDK and not to the dynamically generated headers.  This causes for scenarios where if a nuget SDK only has a partial set of winmds, the headers for the excluded winmds are found in the installed Windows SDK path.  This change fixes that by making CppWinRT_IncludePath and a few include paths that build on it to point to the generated headers location by removing the C++/WinRT SDK path and including the generated headers path.
It would have been ideal to do this in a props, but given we rely on InitDir which is set after our props, I ended up doing this as part of a target.

Fixing CppWinRT_IncludePath and the include paths that build on it to point to the generated headers

---

cppwinrt/code_writers.h
cppwinrt/file_writers.h
cppwinrt/helpers.h
cppwinrt/type_writers.h

WINRT_LEAN_AND_MEAN should not exclude overridable interfaces

---

nuget/Microsoft.Windows.CppWinRT.targets

In #404, we added a property to enable Windows Metadata. We calculate a default is one is not specified, but there are a few cases where we know we should disable it without the need to calculate anything.
If the project specifically set a property to indicate it's a CX project, we will never generate a WinMD and we can therefore set CppWinRTGenerateWindowsMetadata to false.

Add a better default for CppWinRTGenerateWindowsMetadata for CX projects.

---

cppwinrt/code_writers.h

Single-parameter constructors should be explicit

---

strings/base_reference_produce.h
test/test/box_guid.cpp
test/test/test.vcxproj

Support boxing of GUID types for improved interop

---

vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj

Remove the property that indicates if a WinMD is generated.

CoreApp doesn't generate a WinMD

---

cppwinrt/code_writers.h
strings/base_foundation.h
strings/base_identity.h
strings/base_macros.h
test/old_tests/UnitTests/IReference.cpp

A collection of changes to address various issues with IntelliSense usability.
* Use `=` instead of `{ }` for variable templates to workaround IntelliSense bug
* Use `WINRT_IMPL_AUTO` to avoid poor IntelliSense performance due to return type deduction
* Address type conversion warnings from IntelliSense compiler
Also a tweak to avoid brittle ABI headers not defining GUID specializations.
Fixes #384

Workarounds to improve IntelliSense

---

strings/base_coroutine_threadpool.h

On x86 builds, Windows typically requires __stdcall but Clang fails to produce lambda overloads to make this work (as VC helpfully does). This workaround ensures that Clang x86 builds correctly.
Fixes #428

Compatibility with Clang -m32

---

cppwinrt/file_writers.h
test/test/generic_type_names.cpp
test/test/generic_types.cpp

Fixes #446 
The WINRT_LEAN_AND_MEAN optimization causes some trouble for Xaml. It sounds like a Xaml bug but righting that ship is pretty hard. This tweak provides greater compatibility, while reducing the overall benefit of WINRT_LEAN_AND_MEAN a little.

Improve type name compatibility

---

strings/base_types.h

Implement operator< for winrt::guid

---

test/test_win7/guid_key.cpp
test/test_win7/test_win7.vcxproj

The previous PRs to add support for `winrt::guid` keys by implementing `std::hash` and `operator<` (#464, #466) failed to include any tests. Here is a test for these.

Guid key testing

---

strings/base_activation.h
strings/base_agile_ref.h
strings/base_error.h

Some tweaks for Clang conformance. As a bonus, the Clang compiler picked up a source bug.

Clang conformance

---

strings/base_extern.h
strings/base_string.h

Fixes #484
Also deals with warning about conversion rules for arithmetic operations.

Fix regression in Xaml apps

---

nuget/Microsoft.Windows.CppWinRT.targets

CAExcludePath is used to set an environment variable. It looks like the way the build targets override the value might introduce a newline, causing the environment variable to not work. Defining on a single line fixes the issue.
Fixes #492

Remove newline from the CAExcludePath.

---

nuget/Microsoft.Windows.CppWinRT.targets
test/nuget/Directory.Build.props
test/nuget/TestApp/MainPage.cpp
test/nuget/TestApp/pch.h
test/nuget/TestRuntimeComponent2/module.cpp
test/nuget/TestRuntimeComponent3/module.cpp
test/nuget/TestRuntimeComponentCSharp/TestRuntimeComponentCSharp.csproj
test/nuget/TestRuntimeComponentEmpty/module.cpp
test/nuget/TestStaticLibrary1/TestStaticLibrary1.vcxproj
test/nuget/TestStaticLibrary1/TestStaticLibrary1Class.cpp
test/nuget/TestStaticLibrary1/TestStaticLibrary1Class.h
test/nuget/TestStaticLibrary1/TestStaticLibrary1Class.idl
test/nuget/TestStaticLibrary1/pch.h
test/nuget/TestStaticLibrary4/TestStaticLibrary4.vcxproj
test/nuget/TestStaticLibrary4/TestStaticLibrary4Class.cpp
test/nuget/TestStaticLibrary4/TestStaticLibrary4Class.h
test/nuget/TestStaticLibrary4/TestStaticLibrary4Class.idl

Make sure we pass static library references as references to mdmerge for static library projects.

---

natvis/cppwinrt_visualizer.cpp
natvis/cppwinrtvisualizer.vcxproj
natvis/object_visualizer.cpp
natvis/pch.h
natvis/type_resolver.cpp
strings/base_identity.h

Next up: add support for types returning generic interfaces from GetRuntimeClassName (e.g., C++/WinRT collection helpers)

Add support for generic interfaces on non-generic types (runtime classes)

---

nuget/Microsoft.Windows.CppWinRT.targets
test/nuget/NuGetTest.sln
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/CxClass.cpp
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/CxClass.h
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/TestRuntimeComponentCXReferencingWinRTStaticLibrary.vcxproj
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/TestRuntimeComponentCXReferencingWinRTStaticLibrary.vcxproj.filters
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/pch.cpp
test/nuget/TestRuntimeComponentCXReferencingWinRTStaticLibrary/pch.h
test/nuget/TestStaticLibrary7/PropertySheet.props
test/nuget/TestStaticLibrary7/TestStaticLibrary7.vcxproj
test/nuget/TestStaticLibrary7/TestStaticLibrary7.vcxproj.filters
test/nuget/TestStaticLibrary7/TestStaticLibrary7Class.cpp
test/nuget/TestStaticLibrary7/TestStaticLibrary7Class.h
test/nuget/TestStaticLibrary7/TestStaticLibrary7Class.idl
test/nuget/TestStaticLibrary7/packages.config
test/nuget/TestStaticLibrary7/pch.cpp
test/nuget/TestStaticLibrary7/pch.h
test/nuget/TestStaticLibrary7/readme.txt

A WinMD file produced by a static library gets merged into the WinMD of the Dll project consuming the library. Because they often share a root namespace, the files might have the same name and they can overwrite each other in the output folder.
The way this was fixed is to simply remove the static lib from the list of project references. However this causes issues for the case where a CX dll project references a C++/WinRT static library as it doesn't see the reference. A better fix is to mark the reference as private so it won't be copied to the output directory of the Dll project.
Fixes #504

Fix bug where CppWinRT would drop static library references.

---

.gitignore
cppwinrt/code_writers.h
cppwinrt/type_writers.h
test/test/struct_delegate.cpp
test/test/test.vcxproj
test/test_component/test_component.idl

Fixes #509
This is a very obscure edge case, so much so that there has never been a shipping API that has done this. Still, it's good Scott caught it and we can get it fixed.
The fix isn't ideal but it's all I can justify at this stage. A deeper refactoring to somehow make this more generic will have to wait. 
More complete testing will come in the [testwinrt](https://github.com/microsoft/testwinrt) repo.

Fix support for delegates returning arrays of structs

---

strings/base_activation.h
strings/base_agile_ref.h
strings/base_error.h
strings/base_events.h

Fixed #496 
The Clang compiler *still* lacks the Visual C++ support for lambdas with `stdcall` calling convention. This update removes the use of those lambdas where calling convention matters so that the Clang compiler may be used to build x86 binaries.

Support for x86 builds with Clang

---

strings/base_string.h

C++/WinRT is used in places where `memcpy` is no longer permitted.

Avoid using memcpy

---

strings/base_error.h

Libraries in the OS require `winrt::teminate` to be `[[noreturn]]` - I removed the attribute to placate Clang which didn't consider the function as not returning from all paths, but that breaks code unacceptably inside the OS. Instead, I've added a call to `abort` to make Clang happy even though it will never be called.

terminate must be noreturn

---

nuget/CppWinrtRules.Project.xml
nuget/Microsoft.Windows.CppWinRT.props

Reverts microsoft/cppwinrt#520
Need to revert this for now as the OS build doesn't have access to `ole32.lib`.

Revert "Remove use of umbrella libraries"

---

cppwinrt/code_writers.h

as well as to specializations, to avoid inconsistent EBO application, which can also manifest as crashing ODR violations (not just unoptimized code).

Apply EBO declspec to forward declaration 

---

cppwinrt/component_writers.h

Generated component headers (.g.h) and C++ source files (.g.cpp)
are emitted into a _directory structure_ that mirrors the
namespace that the WinRT component is found in.
For instance, for a component such as:
```
namespace Foo.Bar
{
runtimeclass Baz
{
void Frob();
}:
}
```
The .g.h and .g.cpp files will be emitted into a newly created
subdirectory `Foo/Bar` of the output directory given to `cppwinrt.exe`
as the `-out` parameter.
Meanwhile, the component source file (.cpp file, meant to be edited by
the user implementing the component), emits a `#include` that assumes
that the .g.cpp file will be emitted directly in the output directory as
a fully-qualified name of the file. Specifically, the include that is
emitted is:
```
#include "Foo.Bar.Baz.g.cpp"
```
While the file …

Fix include path for generated component (.g.cpp) files

---

strings/base_array.h
test/test/in_params.cpp
test/test/out_params.cpp
test/test_component/Class.cpp
test/test_component/Class.h
test/test_win7/in_params.cpp
test/test_win7/out_params.cpp

For array parameters, ensure that nullptr is not passed as the array base, even for empty arrays. If the array is empty, the array base is not used, but RPC still requires it to be a non-null pointer.
We use a properly aligned non-null pointer as our fake array base, in case somebody cares about alignment.
Note that this fix does not address [out] parameters. The workaround for [out] parameters is more expensive (need to CoTaskMemAlloc(0)) and it is necessary only for out-of-process calls, so I don't want to incur the overhead for everybody. People returning empty com_arrays will have to remain vigilant.
Also fix BO in test Class when asked to fill an empty array.

Do not pass nullptr arrays to the ABI

---

strings/base_collections_vector.h
strings/base_reference_produce.h
test/test/single_threaded_observable_vector.cpp

ReplaceAll did not provide the strong exception guarantee: If not all the elements could be converted to T, the code left the vector in a partially-replaced state. Now it leaves the vector unchanged if the operation fails. (Note that vector_base::assign does not provide the strong exception guarantee if wrapping is required, so we can't quite declare victory yet.)
If the underlying vector is a vector of value types, then attempting to insert nullptr now fails with E_NOINTERFACE rather than crashing.
If the object's runtime type is not T, then IndexOf should report "not found" rather than reporting the index of the first nullptr (if T is a reference type) or crashing (if T is a value type). This fixes issue #518.
Fixed use-after-free bug in test, where we forgot to unregister event …

Fix holes in IObservableVector<IInspectable>

---

strings/base_string.h
test/test/hstring_empty.cpp

Some existing code relies on data returning a valid string even when the view is empty.

Harden operator wstring_view

---

cppwinrt/cmd_reader.h
strings/base_includes.h
test/old_tests/UnitTests/StructCodeGen.cpp
test/old_tests/UnitTests/to_hstring.cpp

Tweaks required by Visual C++ team for C++20 conformance.

C++20 conformance

---

strings/base_activation.h
strings/base_error.h
strings/base_types.h
test/old_tests/UnitTests/get_activation_factory.cpp
test/test/hresult_class_not_registered.cpp
test/test/test.vcxproj
test/test/velocity.cpp
test/test_win7/velocity.cpp

Fixes #552 to properly capture and propagate error information from RoGetActivationFactory when fallback fails.
RoGetActivationFactory returns REGDB_E_CLASSNOTREG rather than CLASS_E_CLASSNOTAVAILABLE when activation fails. The target DLL may return CLASS_E_CLASSNOTAVAILABLE from DllGetActivationFactory. That's why a few of the tests needed updating since those tests were relying on the previous behavior where RoGetActivationFactory was sidestepped entirely.

Accurate error propagation from RoGetActivationFactory

---

cppwinrt/code_writers.h

In code-writers, we are looping through a range of type in types, and we emplace_back using that value.
For this reason, we should preallocate memory for the struct using reserve.

Reserve Memory for type

---

cppwinrt/cmd_reader.h
cppwinrt/main.cpp
cppwinrt/text_writer.h
test/catch.hpp

Most files already have switched to use the modern variation, such as "<ctime>", "<cassert>", etc. However, a few files do not, so this PR fixes that.

Replace old headers with modern ones

---

strings/base_array.h
test/old_tests/UnitTests/array.cpp

Add deduction guides for `array_view`.
* If you pass two pointers, then it deduces as the type of the dereferenced pointers.
* If you pass a C-style array, then it deduces as the underlying type of the array, preserving const.
* If you pass a `std::vector`, then it deduces as the value type of the vector, preserving const.
* If you pass a `std::array`, then it deduces as the value type of the array, preserving const.
Curiously, the pre-existing CTAD behavior for initializer-list deduces as the **non-const** value type, even though initializer lists are const. I didn't try to fix that, but maybe we should consider it.
Example: We want to see if a WiFi-Direct OUI is the one assigned to Microsoft.
```cpp
constexpr std::array<uint8_t, 3> MsftOui{ 0x00, 0x50, 0xF2 };
com_array<uint8_t> …
```

Deduction guides for array_view

---

strings/base_collections.h
test/test/fast_iterator.cpp

The built-in iterators for IVector and IVectorView (and more generally anything that has a GetAt method) now support random-access operations. They do not meet all the requirements of a random-access iterator, most notably:
* `reference` is not `value_type&` or `value_type const&`.
* `operator->` is not supported.
Design notes:
* The `value_type` had been misdeclared as `T` (e.g. `IVector<Something>`) rather than the element type (`Something`).
* The `reference` is not actually a reference because the return value of `operator*` must be convertible to `reference`.
* The element index is unsigned so that the relational operators like `<` produce correct results on large containers.
* The `difference_type` is `ptrdiff_t` so that `b-a` and related operations work on large containers.
* …

Random-access iterators over IVector/IVectorView

---

strings/base_implements.h
test/old_tests/Component/Component.idl
test/old_tests/Component/Events.cpp
test/old_tests/Component/Events.h
test/old_tests/UnitTests/factory_cache.cpp

`make_self` now respects `static_lifetime`. I suspect this was overlooked when `static_lifetime` was introduced.

make_self respects static_lifetime

---

strings/base_implements.h
test/old_tests/Component/Events.cpp
test/old_tests/Component/Events.h

Previous code constructed a new object each time, even though only the first call will actually need the constructed object. The second and subsequent calls just throw the object away and return the existing object.
Construct the object only if we have a reasonable chance of actually using it. This is a big win for static-lifetime objects that are expensive to construct.

Improve performance of make_factory with static_lifetime

---

strings/base_agile_ref.h
strings/base_delegate.h
strings/base_error.h
strings/base_implements.h
test/old_tests/UnitTests/weak.cpp

If the source contributes to the module object count, then the weak reference also contributes, so that we do not unload prematurely.
Factored out module lock updating into helper base class `module_lock_updater` with specialization `update_module_lock`. This avoids a lot of code duplication.

Weak references are objects too

---

strings/base_coroutine_foundation.h
test/test/disconnected.cpp

During a `co_await` of an `IAsyncAction` or `IAsyncOperation`, if the completion delegate is released without ever being invoked, then assume that the remote server crashed. Resume the coroutine, and the RPC error will be raised when `await_resume()` calls `GetResults()`.
Note that this behavior applies only to `co_await`. If you manually attach a `Completed` handler, then it is your responsibility to detect server death.
The `disconnect_aware_handler` is basically the same as the lambda we had been using, just with the additional behavior of resuming the coroutine if it is destructed without ever having been invoked. We null out the coroutine handle on invoke. That lets us detect the error case in our destructor.
This fixes issue #600

Detect RPC server crash when co_await'ing

---

strings/base_weak_ref.h
test/old_tests/UnitTests/weak.cpp

This compares whether the weak references are copies of each other, not whether they refer to the same object.

weak_ref<T> can be compared for equality

---

cppwinrt/component_writers.h

Follows #610 to remove remaining utf-16 strings from component binaries.

Remove remaining utf-16 encoded runtime names from components

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
strings/base_foundation.h
strings/base_identity.h
strings/base_implements.h
strings/base_string.h
strings/base_types.h
strings/base_windows.h
strings/base_xaml_typename.h
test/old_tests/UnitTests/constexpr.cpp
test/old_tests/UnitTests/string_view_compare.h
test/old_tests/UnitTests/xaml_typename.cpp
test/test/enum.cpp
test/test/generic_types.h
test/test/names.cpp
test/test_win7/enum.cpp
test/test_win7/generic_types.h
test/test_win7/names.cpp

Although beneficial for almost all projects, Xaml depends heavily on utf-16 strings and this change ends up hurting WinUI's binary size. 
This change merely reverts the two PRs that carried the utf-8 optimizations #610 and #617

Revert utf-8 encoding of runtime class names

---

strings/base_array.h
test/old_tests/UnitTests/array.cpp

`com_array<T>` can now be constructed from the following, where `U` is convertible to `T`:
* `std::vector<U>`
* `std::array<U, N>`
* C-style array of `U`.
* `std::initializer_list<U>`
(Initialization from a pair of iterators to `U` was already supported. This change extends the behavior to the other collection types.)
Deduction guides have been added to permit class template argument deduction as follows:
* `com_array(N, U)` deduces `T = std::decay_t<U>`
* `com_array(InIt, InIt)` deduces `T = std::decay_t<std::iterator_traits<InIt>::value_type>`
* `com_array(std::vector<U> const&)` deduces `T = std::decay_t<U>`
* `com_array(std::array<U, N> const&)` deduces `T = std::decay_t<U>`
* `com_array(U const(&)[N])` deduces `T = std::decay_t<U>`
* `com_array(std::initializer_list<U>)` deduces `T = …

Improve com_array construction

---

strings/base_coroutine_foundation.h
test/old_tests/UnitTests/async_cancel.cpp

Other projections report cancellation via the Status property and Completed delegate, rather than by GetResults. Switch from GetResults to Status and Completed to detect cancellation, to improve interop.
To avoid unnecessary fetches of the Status property (which are virtual calls), we cache the status passed to the Completed delegate. This applies to `co_await`, `get()`, and `when_any()`. `when_all` is built out of `co_await`, so it gets cancellation interop for free.
Factored cancellation checking into helper function `check_status_canceled`. And factored "create a delegate but give me access to the functor that the delegate is wrapping" into helper function `make_delegate_with_shared_state`. This saves an allocation in `when_any`. Would be nice if this functionality were exposed in the …

Improve async cancellation interop

---

strings/base_coroutine_foundation.h
test/test/when.cpp

* Fix the case where you call `when_all` with coroutines whose return values have an overloaded comma operator. The existing code would accidentally comma the coroutine results together instead of discarding them as intended. Fix by explicitly comma-ing with void. You cannot overload   the comma operator when void is one of the parameters, so this forces the built-in comma operator to be used.
* Fix the case where you call `when_all` with no parameter. The existing code would end up with an empty body, which   lacked any `co_await` or `co_return` statements and therefore   wasn't a coroutine any more. Fix by adding a `co_return`.

Edge cases in when_all

---

strings/base_coroutine_foundation.h
test/test/when.cpp

Can just cast to void() instead of having to comma with void.
Comma-avoidance test no longer requires PPL.

Simply when_all implementation and test

---

cppwinrt/code_writers.h
cppwinrt/cppwinrt.vcxproj
cppwinrt/cppwinrt.vcxproj.filters
strings/base_coroutine_system_winui.h

Fixes #578 
WinUI 3 has a distinct `DispatcherQueue`. This update provides `resume_foreground` support for it if you're targeting WinUI 3 and include the generated `winrt/Microsoft.System.h` header.

Add support for the WinUI DispatcherQueue

---

strings/base_abi.h
strings/base_implements.h
test/old_tests/Component/Events.cpp

Services need to clean up all their COM objects without running down COM. Provide a way to remove a specific factory or factories from the static lifetime store.
```cpp
clear_factory_static_lifetime<Class1, Class2, Class3>();
```
The classes must be factory classes (in the `factory_implementation` namespace), to match `make_self`. We use the `instance_class` subtype to verify this.
This fixes issue #651

Can clear a specific factory from static lifetime store

---

strings/base_reference_produce.h
test/old_tests/UnitTests/Boxing2.cpp

In a call to `unbox_value_or<T>(obj, def)`, if the second parameter happens to be a valid constructor parameter for `param::hstring`, then the hstring version of `unbox_value_or` will be used, even though the user clearly wants `T`.
```cpp
// expected to unbox obj to an IPropertyValue,
// but actually unboxes to an hstring!
auto pv = unbox_value_or<IPropertyValue>(obj, {});
```
Add an explicit `enable_if` to remove the hstring version if the template parameter is not `hstring`.
There's the converse problem, where you want `unbox_value_or` to infer `hstring`, but it can't:
```cpp
// Doesn't compile due to inability to infer T.
auto str = unbox_value_or(obj, hstring{});
```
Add a default type `hstring` for `T` in the hstring version of `unbox_value_or`.

Fix unbox_value_or problems with explicit type and implicit hstring

---

cppwinrt/code_writers.h
strings/base_collections_base.h
strings/base_error.h
test/old_tests/UnitTests/TryLookup.cpp
test/old_tests/UnitTests/produce_map.cpp
test/old_tests/UnitTests/single_threaded_map.cpp

`single_threaded_map()`'s IMap::Remove did not throw `hresult_out_of_range` on attempts to remove a nonexistent key. Now it throws.
Note that this is a breaking change. Code that assumed nonexistent objects could be harmlessly removed will encounter exceptions when run against C++/WinRT implementations when they hadn't before this change. This was, however, a pre-existing bug, because implementations from other projections (C#, C++/CX, WRL) always throw under those conditions.
Added a TryRemove() method for people who want the nonthrowing version.
Note that fixing the ABI conformance is required in order for TryRemove to return the correct result, because TryRemove relies on the call to Remove failing if the key doesn't exist.
(JavaScript doesn't project objects as maps, so there is …

Fix ABI conformance of IMap::Remove, add TryRemove

---

nuget/Microsoft.Windows.CppWinRT.props

Current released versions of MdMerge don't like duplicate definitions. This PR attempts to reduce the duplication by not copying reference output to the output folder by default unless this is an application. An application is always a leaf node and its winmd should never be merged into something else anyway. 
Overrides are still possible since this is defined in the props file which is imported very early in the build process, to allows folks to change the default if needed. Unit test projects are an example where this might be needed, but there is not a good way to detect them. 
A non-C++/WinRT project won't get these defaults and those projects might still require manually setting Private=false, if it is reference by a C++/WinRT project, so this solution isn't perfect but it helps …

Set better defaults for references and project references to keep MdMerge happy.

---

strings/base_coroutine_foundation.h

C++ static analysis in VS 2019 warns that these should be noexcept.

Make disconnect_aware_handler ctor and move ctor noexcept.

---

strings/base_array.h
test/old_tests/UnitTests/array.cpp

Addressing #665 by promoting the `array_view(pointer, size)` constructor to be public rather than protected, which is consistent with C++20's `std::span` that `winrt::array_view` is designed to emulate.

Make array_view(pointer, size) constructor public

---

strings/base_coroutine_foundation.h

Fixes #659
Note that full Clang support is currently hampered by the fact that Clang doesn't like the current VC libraries and fails to compile them. Other than that, this update fixes two minor issues that Clang didn't like about recent changes to C++/WinRT.
```C++
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\xutility(63,5): error : non-void constexpr function '_Bit_cast' should return a value [C:\git\cppwinrt\scratch\scratch.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\charconv(1196,15): error : no matching function for call to '_Bit_cast' [C:\git\cppwinrt\scratch\scratch.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\charconv( …
```

Support for LLVM 10

---

strings/base_coroutine_foundation.h
test/test/async_completed.cpp
test/test/test.vcxproj

If the Completed handler runs synchronously, that would cause us to destroy the operation while a method on the operation is still running. That's not very nice.
This stems from the fact that synchronous completion causes the coroutine to resume before put_Completed returns. Resuming the coroutine causes it to get the result and then destroy the async operation. If the Completed handler is called synchronously from within put_Completed (which will happen if the operation has already completed), the operation will be destroyed while the put_Completed call is still outstanding. To avoid this problem, await_suspend extends the lifetime of the async operation across the call to put_Completed, so that the synchronous completion doesn't destroy the async operation prematurely.
If the operation …

Don't destroy the IAsyncInfo from inside Completed handler

---

strings/base_coroutine_foundation.h
test/test/async_progress.cpp

This is useful when you are wrapping another operation's progress, as is common with HTTP filters.
```cpp
auto operation = m_inner.SendRequestAsync(request);
operation.Progress([progress_token = co_await get_progress_token()](auto&&, HttpProgress progress)
{
progress.Retries += retries_performed;
progress_token(progress);
});
co_await operation;
```

make progress_token::operator() const so it can be captured by lambdas

---

strings/base_coroutine_foundation.h
test/test/async_auto_cancel.cpp
test/test/async_cancel_callback.cpp

Allow revoking cancellation callback by setting it to null. This is important if a late callback could end up accessing an already-destructed object. Previously, the only way to revoke a cancellation callback was to replace it with a nop delegate `[]()`, which is clunky.
Make the token's callback method const. This makes it easier to capture a token into a lambda.

Cancellation token improvements

---

strings/base_string.h
strings/base_string_operators.h
test/old_tests/UnitTests/hstring.cpp

The zero-length string is represented by nullptr, not a heap-allocated string of length zero.

Fix concat_hstring for 0-length string

---

fast_fwd/arm64/thunks.asm

Unlike other architectures, on ARM64 __guard_check_icall_fptr follows a custom calling convention. X15 takes the address of the target method and that value is preserved across the call.
As a result, there is no need to enlist the help of the x19 non-volatile register. In turn, no need to spill/fill it.

[ARM64] Fix CFG helper calling convention and simplify flow of call target address.

---

build_nuget.cmd
nuget/Microsoft.Windows.CppWinRT.nuspec
nuget/Microsoft.Windows.CppWinRT.targets
nuget/readme.md

This resolves #677 by:
* Including WinMDs found from `ExpandSDKReference`
* Adding some instructions on build & test for the nuget packages
* Ensuring nuget packages are built with the passed-in version  number

Add SDKReference-sourced WinMDs when building

---

strings/base_coroutine_threadpool.h
test/test/async_ref_result.cpp
test/test/test.vcxproj

`auto await_resume()` will decay the return value, causing references to turn into values. Use `declspec(auto)` to preserve references when wrapping other coroutines.

Support coroutines returning references

---

cppwinrt/code_writers.h
cppwinrt/cppwinrt.vcxproj
cppwinrt/cppwinrt.vcxproj.filters
cppwinrt/file_writers.h
strings/base_version.h
strings/base_version_odr.h

The existing mismatch detection catches the case where a single *.cpp file includes headers from different versions of the C++/WinRT headers. However, the error message isn't very helpful in tracking down the two versions that didn't match.
Move the `#define` of `CPPWINRT_VERSION` outside the header guard and repeat the definition after the `static_assert`.  This makes mismatches easier to diagnose because the compiler will tell you
```
apple\base.h(3) warning: CPPWINRT_VERSION: macro redefinition
banana\base.h(3) note: see previous definition of CPPWINRT_VERSION
```
in the case where you `#include` two incompatible versions of `base.h`, or
```
apple\Windows.UI.h(6) error: Mismatched C++/WinRT headers.
apple\Windows.UI.h(7) warning: CPPWINRT_VERSION: macro redefinition
banana\base.h(3) …
```

Improve detection of mismatched header versions

---

strings/base_delegate.h
test/test/pch.h

Delegates derive from app-provided classes, which means that any function parameter in the delegate methods could potentially hide a member from the app-provided class. Delegates don't actually care because the only thing from the base class they use is the function call operator, which isn't a named member.
Disable the warning to avoid triggering false alarms in projects that build with all warnings enabled.

Disable warning 4458 in delegates

---

strings/base_error.h
strings/base_types.h
test/old_tests/UnitTests/TryLookup.cpp

XAML's ResourceDictionary has a custom implementation of `IMap` that returns `E_FAIL` and `HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND)` to indicate that the key is not present. Accommodate this nonstandard behavior.
Fixes #685

Accommodate other "key not found" errors

---

strings/base_error.h

Otherwise the mistake isn't detected until the call to RoOriginateLanguageException, at which point the reason for the assertion failure is not obvious.
Fixes issue #680

diagnose throw_hresult(success_code) better

---

strings/base_coroutine_threadpool.h

The apartment-switching function `resume_apartment_sync` takes a context and a coroutine handle and resumes the coroutine in that context. The context is taken by reference, which is a problem if the coroutine resumption is going to destruct the context: We destruct the context while its call to `ContextCallback` is still active.
The awaiter for `IAsync*` captures the context into the completion handler, which is a separate object from the coroutine, so resuming the coroutine will not destruct the context.
However, the awaiter for `apartment_context` uses the context stored directly inside the `apartment_context` itself, which could be destructed as part of resumption:
```cpp
fire_and_forget Something()
{
// Delay 1 second and return to original context.
{
apartment_context save;
co_await …
```

Don't free the apartment_context while we are still using it

---

strings/base_com_ptr.h
strings/base_meta.h
strings/base_reference_produce.h
strings/base_windows.h
test/old_tests/UnitTests/Boxing2.cpp
test/old_tests/UnitTests/boxing.cpp
test/old_tests/UnitTests/com_ptr.cpp

This permits fluent usage, which lets you read the code left-to-right instead of prefix usage which forces the eyes to dart back and forth.
Example of using `as` instead of `unbox_value`:
```cpp
// old and busted with unbox_value()
auto h = unbox_value<Size>(SelectedItem().Tag()).Height;
auto h = unbox_value<Size>(propertySet.Lookup(L"key")).Height;
// new hotness with as()
auto h = SelectedItem().Tag().as<Size>().Height;
auto h = propertySet.Lookup(L"key").as<Size>().Height;
```
Example of using `try_as` instead of `unbox_value_or`:
```cpp
// old and busted with unbox_value_or()
auto h = unbox_value_or<Size>(SelectedItem().Tag(), default_size).Height;
auto h = unbox_value_or<Size>(propertySet.TryLookup(L"key"), default_size).Height;
// new hotness with try_as() + std::optional
auto h = …
```

Add value type support to as() and try_as()

---

strings/base_chrono.h
test/old_tests/UnitTests/clock.cpp

Enable conversion between winrt::clock and std::chrono::system_clock

---

strings/base_collections_base.h
strings/base_collections_input_map.h
strings/base_collections_input_vector.h
strings/base_collections_map.h
strings/base_collections_vector.h
strings/base_coroutine_foundation.h
strings/base_lock.h
test/test/multi_threaded_common.h
test/test/multi_threaded_map.cpp
test/test/multi_threaded_vector.cpp
test/test/test.vcxproj

This mainly re-uses the existing collections, but adds support for doing shared/exclusive operations. For the existing single threaded collections, nothing special is done and operations are performed without any synchronization. For the new multi-threaded collections, an SRWLOCK is acquired in either shared or exclusive mode.
The most noteworthy "flaw" is that mutating iterator operations lock the collection exclusively. This is mostly a limitation imposed by the base IIterable type which uses opaque iterators for the IIterator objects. In theory, the collection only needs to be locked in shared mode, however that would require the IIterator objects themselves to have a separate lock, which seemed like overkill and unlikely to be worth it. Compare this to the existing ABI collection …

Add multi-threaded collections

---

strings/base_coroutine_threadpool.h
test/test/notify_awaiter.cpp

Previous error message was
```
error C2672: 'get_awaiter': no matching overloaded function found
```
New error message is
```
error C2338: Not an awaitable type
```
If you `co_await` something that has both a member `operator co_await` as well as a free `operator co_await`, the error message used to be
```
error C2668: 'winrt::impl::get_awaiter': ambiguous call to overloaded function
```
and it is now
```
error C2338: Ambiguous operator co_await (as both member and free function)
```
The C++ standard has rules for resolving the ambiguity, but they are difficult to express in template metaprogramming, so we don't try and simply reject them. Hasn't been a problem yet. Added some ambiguous awaiters to the unit tests to verify that we resolve to the correct one in the cases we support.
Remove …

Improve error message if you co_await a non-awaitable

---

strings/base_error.h

The OS version of RoOriginateLanguageException converts empty messages into an error message produced by FormatMessage. Our fallback Win7 version does not have this feature, which causes errors to be produced with no message.
This defect had been present since inception but was exposed by a correctness fix to `hstring.c_str()` so that it returned an empty string (instead of nullptr) for the null hstring.
Prior to the hstring fix, the implementation of `error_info_fallback::GetErrorDetails` would happily pass `nullptr` to `SysAllocString`, which failed with an invalid parameter. This error was propagated (mistakenly as `error_bad_alloc`), and that caused `hresult_error.message()` to fall back to `FormatMessage`.
With the hstring fix, the implementation of …

error_info_fallback needs to convert empty message

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
cppwinrt/file_writers.h
cppwinrt/helpers.h
cppwinrt/type_writers.h

Instead of having everybody just whack state variables (which results in a rats nest of "I don't know what state I'm in any more"), use RAII types to scope the state changes.
The changes for `abi_types` exactly match the previous behavior, except that `abi_types` is now `false` during the generation of `write_forward` for forward declarations of types from other namespaces, when it used to be `true`. Fortunately, it doesn't seem to matter, since those forward types don't appear to be affected by the setting of `abi_types`.
Cannot use RAII types for the file guards because we generate the bottom half of the header file before the top half.
The state of `param_names` in `component_writers.h` is still somewhat unclear, so I left that part alone.
Verified that all generated header files (both …

Use RAII to keep better track of code generation state

---

test/test/multi_threaded_map.cpp
test/test/multi_threaded_vector.cpp

The concurrency tests for multi-threaded collections run for a nondeterministic number of iterations, and the branches taken within the test are nondeterministic, causing the REQUIRE macro to be called a nondeterministic number of times during the run of the test. This means that each time you run the tests, the numbers in the message
```
All tests passed (314159 assertions in 2718 test cases)
```
are different. This does not contribute to confidence that the tests are working.
There is also a problem with the REQUIRE macro: It does not support concurrent usage from multiple threads. If two threads perform a REQUIRE at the same time, the assertion count is unreliable.
Fix both problems by not using REQUIRE (1) in nondeterministic ways or (2) from multiple threads simultaneously. Instead, …

Make test reports deterministic in the face of nondeterminism

---

strings/base_coroutine_foundation.h

Reading the status of an IAsyncXxx does not require a lock because the operation is already inherently racy. Change the `m_status` to a `std::atomic` so we can access it from multiple threads without a lock. Everybody who accesses it under a lock can use `std::memory_order_relaxed` because the lock is providing the memory ordering protection. The `Status()` method uses acquire order to handle the case where one thread publishes the IAsyncXxx with release semantics, and another thread picks it up and interrogates the status. Causality requires us to report the status that was published by the first thread, so we need acquire.
Reading the value while another thread is changing it is okay, as long as we get either the entire old value or the entire new value, which is what `std::atomic` …

Status() doesn't need a lock

---

nuget/Microsoft.Windows.CppWinRT.targets

Delete the rsp files on error and be smarter about detecting deleted input files, by using a technique similar to what the C# compiler is using here: https://github.com/dotnet/msbuild/blob/0e7b70f663ab86af7ab41d5d7b409f72f7143899/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3397-L3427
Fixes #706 
TODO:

Delete the rsp files on error and be smarter about detecting deleted files.

---

test/test/multi_threaded_common.h
test/test/multi_threaded_map.cpp
test/test/multi_threaded_vector.cpp

Instead of running 100,000 iterations hoping to hit a race condition, use an instrumented vector/map that lets us inject delays into specific operations, and which detects concurrency violations. This allows us to force specific race conditions rather than waiting for them to happen.
This reduces the running time of the multi* tests from 80 seconds to 1.5 seconds, as measured on a Surface Pro 5 (dual Core-i5 7300U).
You can flip the #if at the top of multi_threaded_vector.cpp and multi_threaded_map.cpp to force the test to use a single-threaded collection and observe that the race conditions are hit.

Use instrumented vectors/maps in tests to force race conditions more efficiently

---

test/old_tests/UnitTests/array.cpp

The Web site https://moderncpp.com/ is having certificate problems, which is causing the array test to fail, since the array test pings the Web site's RSS feed.
Change to use a JsonArray, which removes a non-essential networking dependency.

Remove network dependency from array test

---

strings/base_implements.h
test/test/no_make_detection.cpp
test/test/test.vcxproj
test/test_component/Class.cpp
test/test_component/Class.h
test/test_component/pch.h
test/test_component/test_component.idl
test/test_win7/no_make_detection.cpp
test/test_win7/test_win7.vcxproj

Mismatching `WINRT_NO_MAKE_DETECTION` results in inconsistent vtables and very confusing runtime crashes. Detect the problem at link time.
`pragma detect_mismatch` must occur at global scope, so we float it to the top of `base_implements.h` even though it would more logically be placed at the point of declaration of the bonus virtual member.
This change uncovered the fact that `test` and `test_win7` had portions built with and without `WINRT_NO_MAKE_DETECTION`, so it was already violating ODR. Moved the `WINRT_NO_MAKE_DETECTION` to the test component and make the entire test component enable `WINRT_NO_MAKE_DETECTION`.
The symbol `WINRT_LEAN_AND_MEAN` does not require ODR protection because it excludes entire functions and classes, rather than rewriting pieces of existing functions and …

Add ODR detection to WINRT_NO_MAKE_DETECTION

---

test/test/multi_threaded_common.h

This type is instantiated by the deleted constructor whose original purpose is to allow an implicit conversion from non-const iterator to const iterator. When applied to the const iterator itself, it enables an implicit conversion from garbage to const iterator. The conversion is deleted, but the compiler still instantiates it, so we define the type to keep everybody happy.

Multithreading tests: Add dummy definition to keep compiler happy

---

nuget/Microsoft.Windows.CppWinRT.targets

Fixes #741 
This is hit when forcing proc count in msbuild since /MP should also imply /FS (force synchronous writes) but that enforcement is done by `FixupCLCompileOptions` after all other `ComputeCompileInputsTargets` runs. If something runs after the fix up has already happened, we break the build (`Error C1041: cannot open program database`)

Targets that add compiler options must run before FixupCLCompileOptions

---

nuget/CppWinrtRules.Project.xml
nuget/Microsoft.Windows.CppWinRT.props
nuget/readme.md

Set Private explicitly to false for certain projects instead of setting it to false for everything and then setting it true for certain projects and allow projects to opt-out.
TODO:

Set Private to false for specific projects instead of everything.

---

strings/base_coroutine_foundation.h
strings/base_coroutine_threadpool.h
strings/base_extern.h
strings/base_includes.h
test/test/async_propagate_cancel.cpp
test/test/test.vcxproj

The cancellation token learned a new method `enable_propagation()`. It takes an optional boolean parameter (default true) which specifies whether propagation of cancellation into child coroutines is enabled. It returns the previous setting, in case you want to restore it.
If cancellation propagation is enabled in a coroutine, then calling `IAsyncXxx.Cancel()` on the coroutine's asynchronous activity will try to propagate the cancellation into whatever the coroutine is `co_await`ing for. Currently, the following awaitables are supported:
* `IAsyncXxx`
* `resume_after()`
* `resume_on_signal()`
Example:
```cpp
IAsyncAction<bool> CheckAsync()
{
// Enable cancellation propagation.
auto cancel = co_await get_cancellation_token();
cancel.enable_propagation();
HttpClient client;
auto result = …
```

Allow cancellation to be propagated to child coroutines

---

scratch/scratch.vcxproj
strings/base_coroutine_foundation.h
strings/base_coroutine_system.h
strings/base_coroutine_system_winui.h
strings/base_coroutine_threadpool.h
strings/base_coroutine_ui_core.h
strings/base_deferral.h
strings/base_includes.h

Fixes #676
With this update, C++/WinRT supports both C++17 with `/await` as well as C++20 coroutine support.

C++20 coroutine support

---

strings/base_coroutine_threadpool.h

VS 2017 requires an accessible copy constructor even though it is never used. Turns out we're okay with `enable_await_cancellation` being copied, as long as it's not copied while awaiting (which we don't do). So go ahead and let it be copyable.
VS 2017 also reports an unused variable error when the use of the `promise` is removed via `if constexpr`. Mark it as `[[maybe_unused]]` to help the compiler.

VS 2017 compatibility for enable_await_cancellation

---

nuget/Microsoft.Windows.CppWinRT.targets
nuget/readme.md

Remove /await flag for compat with C++20

---

strings/base_coroutine_foundation.h
strings/base_coroutine_system.h
strings/base_coroutine_system_winui.h
strings/base_coroutine_threadpool.h
strings/base_coroutine_ui_core.h
strings/base_deferral.h
strings/base_macros.h

Define co_await operators for C++20 coroutines

---

nuget/Microsoft.Windows.CppWinRT.targets

Use the CppWinRTPlatformWinMDReferences itemgroup as the input for the platform projection.

---

strings/base_activation.h
test/old_tests/UnitTests/get_activation_factory.cpp

We have a design pattern "extension classes" that uses runtimeclasses as extensions. The class names are discovered at runtime, so we need to be able to specify them to the activation functions. this adds that support.

add try_get_activation_factory overloads that take the runtimeclass name

---

test/old_tests/Composable/Composable.vcxproj

I found with no code changes "build" re-built this project. Using the detailed msbuild output I found Component.winmd was always detected as missing. 
```
3>Project is not up-to-date: build input 'c:\users\chris\source\repos\chrisguzak\cppwinrt\test\old_tests\composable\composable.winmd' is missing.
```
This seems to be due to using the undefined `$(OutputDirectory)` in the custom build. I change this to `$(OutDir)` and incremental build works.

Fix incremental build of tests/old_tests/composable

---

nuget/CppWinrtRules.Project.xml
nuget/Microsoft.Windows.CppWinRT.props
nuget/Microsoft.Windows.CppWinRT.targets
nuget/readme.md

This is the last stable version that was ingested into the OS.

Revert nuget to 2.0.200609.3

---

strings/base_chrono.h

When `_USE_32BIT_TIME_T` is defined, `time_t` is 32-bit rather than 64-bit. This is not recommended and seldom used, but does come up from time to time. This change simply avoids a build error if this occurs by forcing the conversion.

Support _USE_32BIT_TIME_T

---

cppwinrt/cmd_reader.h

https://task.ms/29349404 - The SDK sometimes stores the 64 bit location into KitsRoot10 which is wrong,
This breaks 64-bit cppwinrt.exe, so work around this by forcing to use the WoW64 hive.

Fix x64 builds of cppwinrt to properly locate the SDK

---

strings/base_reference_produce.h
test/test/box_delegate.cpp
test/test/test.vcxproj

This used to work but was blocked when this assert was added. There's probably a less restrictive assert that would be beneficial but I couldn't get a simple example working quickly and I need this to unblock the Windows build.

Support boxing delegates

---

cppwinrt/code_writers.h
strings/base_activation.h
strings/base_array.h
strings/base_com_ptr.h
strings/base_events.h
strings/base_handle.h
strings/base_security.h
strings/base_string.h
strings/base_windows.h
test/old_tests/UnitTests/properties.cpp

Common porting error coming from languages that have properties as native concepts is trying to set a C++/WinRT property by doing
```cpp
o.Property() = value;
```
due to overzealous application of the rule "In C++/WinRT, you access a property by doing `o.Property()`."
Fix this by making all assignment operators require the assigned-to variable to be an lvalue, rendering the above mistake a compile-time error.
Assigning to an rvalue is not interesting because the rvalue has no name, so you have no way of using the assigned-to object. There are some wacky fringe cases where you might be doing this on purpose:
```cpp
get_abi(hstring() = L"Hello")
```
gives you an ABI string handle for a temporary. But this is decidedly non-idiomatic and I'm fairly confident nobody does this on purpose. The …

Prevent inadvertent assignment to temporary object

---

nuget/Microsoft.Windows.CppWinRT.targets

This PR fixes a bug in the GetResolvedWinMD target that causes a relative path to be returned by the Build target causing problems when the target started the build tries to resolve the output.
Fixes #809 and https://github.com/dotnet/msbuild/issues/5412

Return the full path to the generated WinMD.

---

strings/base_types.h
test/test/generic_types.h
test/test_win7/generic_types.h

Supersedes #829.
- Migrate logic from `generic_types.h` (test projects) to `winrt/base.h`.
- Support for `std::wstring_view`.
- Address std::string_view ->winrt::guid parsing in #797.

Define guid constructor to parse string_view

---

strings/base_error.h
strings/base_extern.h
test/test/custom_error.cpp

#841
This change is being made to improve the interop between cppwinrt and WIL (particularly WIL's logging abilities for errors). It introduces a hook to the `winrt::throw_hresult` method that <wil/cppwinrt.h> will be able to fill in with a valid function pointer. That function pointer will allow WIL's logging abilities to gain knowledge of the exceptions that are originated within cppwinrt.
An extern function pointer was created which is empty by default. If it is set then `winrt::throw_hresult` will call it before continuing with actually throwing the exception.
One interesting note is that several of the parameters to `winrt_throw_hresult_handler` are not actually filled in. There is an expectation that [C++20 source_location](https://en.cppreference.com/w/cpp/utility/source_location) …

Add a hook to throw_hresult for integration with WIL

---

strings/base_error.h

At a minimum, avoid build breaks on non-MSVC compilers.
Turns out that gcc, clang, icc, djgpp, ellcc, and zapcc all define the symbol `__GNUC__` and support the gcc return address extraction extensions. So we need only test two symbols: `_MSC_VER` for MSVC, and `__GNUC__` for everyone else.
clang and icc implement the gcc extensions for compatibility. djgpp is built on top of gcc, so it inherits the gcc extensions. ellcc and zapcc are built on top of clang, so they inherit the gcc extensions via clang.
For MSVC, you must include `intrin.h` before using `_ReturnAddress()`, so we do that explicitly. rather than relying on the kindness of strangers (in this case, relying on apps having the `WindowsNumerics.impl.h` header file installed and leaving `_XM_NO_INTRINSICS_ ` undefined, so that …

Make return address extraction build (and even work) on non-MSVC compilers

---

strings/base_coroutine_threadpool.h
test/old_tests/UnitTests/apartment_context.cpp

In PR #662, we changed the way we switch from STA to NA by bouncing through the threadpool so that we don't run the NA on an STA thread.
We extend this behavior to switches from STA to STA, to avoid RO_E_BLOCKED_CROSS_ASTA_CALL exceptions, which has been identified as the source of some crashes.
Interestingly, we add this support by deleting code. We would normally add tests for STA and MAINSTA to the NA test, but since MTA was ruled out by the previous test, and NA+STA+MAINSTA completely cover all the non-MTA possibilities, there's no need to perform any test at all. The fact that we got here means that the destination is NA/STA/MAINSTA.
Note also that the first test in this block checks if we are resuming in the same apartment that we are currently in. That test is important, because it …

Always bounce through the threadpool when switching from STA

---

strings/base_error.h
strings/base_extern.h
test/old_tests/UnitTests/hresult_error.cpp
test/test/custom_error.cpp

Handy for logging. This complements to_hresult().

to_message() function extracts exception text from catch(...)

---

strings/base_coroutine_threadpool.h
test/old_tests/UnitTests/apartment_context.cpp

Constructing an apartment_context with nullptr creates an empty apartment context that cannot be used for anything, but you can later assign another apartment context to it.
This is handy if you don't want to capture the apartment context right now, but you have to declare the variable right now. For example, member variables are constructed when the containing class is constructed, even though you may not want to capture the apartment context until later.
Prior to this fix, you had to use std::optional to defer the construction of the apartment_context.
It's unfortunate that adding std::move support is so wordy.
We take advantage of this in the unit test itself: The code to generate an apartment_context from a IContextCallback, for example, needs to predeclare an empty apartment_context …

Allow empty apartment_contexts

---

strings/base_error.h
strings/base_types.h

* Versions of STL typically used with Clang don't corrently attribute `std::terminate` with `[[noreturn]]`.
* Clang incorrectly fails to see the static constexpr member.

Clang workarounds

---

strings/base_coroutine_foundation.h
test/old_tests/UnitTests/async.cpp
test/test/async_progress.cpp
test/test/async_result.cpp
test/test/async_suspend.cpp
test/test/pch.h
test/test_win7/async_result.cpp
test/test_win7/async_suspend.cpp
test/test_win7/pch.h

Clients of IAsync...WithProgress are permitted to call GetResults() before the operation has completed, allowing them to observe partial results. This behavior is necessary because the Progress type must be a value type, but the operation may want to report reference types in their progress reports. The way to do that is to report the reference type as the GetResults().
The coroutine itself can use the `set_result()` method on the progress token to report a result prior to completion, and can set a new intermediate result as often as desired prior to the completion of the coroutine. The value passed to `co_return` acts as the final result of the coroutine. If `set_result()` is never called, then the intermediate result is an empty result (null for reference types, default-initialized for …

Allow IAsync...WithProgress to report intermediate results

---

cppwinrt/main.cpp
cppwinrt/text_writer.h

Fixes #877 
(moving from remote branch PR in #877)
React Native for Windows creates apps that can end up with some paths that need to be built that are too long (e.g. `C:\users\myname\source\repos\MyAppProject\node_modules\react-native-windows\Microsoft.ReactNative\Generated Files\winrt\Insert.Your.Favorite.Long.Namespace.Here.h` ). We see lots of issues where people are creating their project starting in an already pretty deeply-nested folder, and the build fails. 
The reason the build fails is because certain headers that cppwinrt is supposed to generate are not on disk. After tracing this down, it turns out that this comes from the fact that the `std::ofstream` constructor does not throw on error. Instead, it will set its internal handle to null, and you have to check …

Don't fail file open/writes silently

---

cppwinrt/app.manifest
cppwinrt/cppwinrt.vcxproj
cppwinrt/cppwinrt.vcxproj.filters
cppwinrt/main.cpp

In #880 we had a hacky way to enable long path support; here we do it via manifest
CC @oldnewthing

use app manifest

---

strings/base_coroutine_threadpool.h

Fix support for x86 builds with Clang 

---

nuget/Microsoft.Windows.CppWinRT.targets

I found that if I create a WinRT local server project, a dependent app project won't build due to a missing file referenced in the .appxmanifest (the WinRT local server registration information that I added). The error lead me to this line in the build system that supports `.dll` dependents, but not `.exe`s. Adding the `.exe` test fixes this problem and seems appropriate (experts please advise).
With this change a warning is still produced, it seems to to missing support in the .appxmanifest generation support.
```
warning APPX1708: The executable 'WinRtLocalServer.exe' is specified as the implementation for the .winmd file 'C:\Users\chris\source\repos\ChrisGuzakWork\WinRtLocalServerClient\Debug\WinRtLocalServer.winmd'. 
Only in-process servers are supported for generating registration …
```

To support local servers, use .exe files from dependent projects as Implementation in Microsoft.Windows.CppWinRT.targets

---

strings/base_activation.h
strings/base_com_ptr.h
strings/base_error.h
strings/base_macros.h
strings/base_windows.h

Different toolchains use different ways of marking a function as not inlinable. Wrap it inside a macro so we can accommodate the differences.
Fortunately, all of them insert the marker at the same place (between the "inline" keyword and the return type).

Use compiler-specific WINRT_IMPL_NOINLINE macro for noinline functions

---

strings/base_coroutine_threadpool.h
strings/base_extern.h

Fortunately, the Ex versions behave the same as the Win7 versions, so we can just switch everybody to the Win7 versions.
Fixes #894

Restore Win7 compat by using old versions of threadpool functions

---

strings/base_com_ptr.h
test/old_tests/UnitTests/capture.cpp

This saves the hassle of having to wrap the raw pointer inside a temporary com_ptr or a lambda.
This PR is in two commits. The first is a refactor so that all the capturing functions funnel through to a single `capture_to`.
The second is the one that adds `capture_to` support for capturing from a raw pointer.

Allow capturing from a raw pointer

---

strings/base_activation.h
strings/base_agile_ref.h
strings/base_coroutine_threadpool.h
strings/base_error.h
strings/base_events.h
strings/base_extern.h

Win7 cannot cancel threadpool timers or threadpool waits atomically, so we simply disable cancellation of resume_after and resume_on_signal when running downlevel. Sorry, Win7.
Most of the work in this PR is updating `load_runtime_function` so is no longer hard-coded to combase.

Restore Win7 functionality (more correctly this time)

---

strings/base_reference_produce.h
test/test/box_array.cpp
test/test/test.vcxproj

The boxing and unboxing functions now support most kinds of arrays. The notable exception is arrays of enumerations. Nothing technically preventing it. Just lazy.
You can box and unbox arrays nearly anywhere you could box and unbox scalars, with one exception: You cannot unbox arrays with `unbox_value_or`. The reason is that `com_array` is not copyable, and `unbox_value_or` returns a copy of its second parameter on failure. We could try to address this by having `unbox_value_or` accept its second parameter as an `array_view` when asked to unbox an array type. But I didn't try. Just lazy.
One annoyance is the treatment of `com_array<GUID>`. This is identical to `com_array<guid>` but I had to play games to convert between them efficiently. Maybe it wasn't worth it. Perhaps I should have …

Add support for boxing and unboxing most kinds of arrays

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
cppwinrt/type_writers.h
test/test_component/Windows.Class.cpp
test/test_component/Windows.Class.h
test/test_component/test_component.idl
test/test_component/test_component.vcxproj

Fixes #892
Adds a simple test class to ensure this works.

Support nested Windows namespace

---

cppwinrt/code_writers.h
cppwinrt/type_writers.h
test/test_component/Windows.Class.cpp
test/test_component/Windows.Class.h
test/test_component/test_component.idl

@DefaultRyan is this what you had in mind?

Windows test

---

cppwinrt/code_writers.h
test/old_tests/Composable/Base.cpp
test/old_tests/Composable/Base.h
test/old_tests/Composable/Composable.idl
test/old_tests/Composable/Composable_h.h
test/old_tests/UnitTests/Composable.cpp

Fixes #782
I updated the `Composable_h.h` file so there's a lot of noise in there.

Implement support for noexcept overridable methods

---

strings/base_implements.h
test/old_tests/UnitTests/weak.cpp

Originally, factories defaulted to no_weak_ref because there wasn't believed to be any use case for weak references to factories, and the thought was that the weak reference support would be a performance penalty.
In practice, the weak reference support does not have a significant performance impact, so it's okay to leave it on even for factories.
Allowing weak references to factories is important because factories implement the static members of a runtime class, and those members may require taking weak references:
* Event handlers need weak references so that the event handler doesn't create a circular reference back to the factory.
* Queueing work to a background thread takes a weak reference so that the work can be abandoned if the factory has been destroyed. (We don't want to extend …

Factories no longer default to no_weak_ref

---

natvis/cppwinrt.natvis

hresult_error displays the wrapped hresult.
array_view displays the size and the first few elements. It expands to the elements in the view, in the form of an array.

Natvis support for hresult_error and array_view

---

test/catch.hpp
test/nuget/ConsoleApplication1/readme.txt
test/test/velocity.cpp
test/test_win7/velocity.cpp
vsix/ItemTemplates/ViewModel/cppwinrt_ViewModel.vstemplate
vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/readme.txt
vsix/ProjectTemplates/VC/Windows Desktop/WindowsApplication/readme.txt

Note that this change only impacts comments and metadata, not actual code.

Fix few typos in comments

---

strings/base_implements.h
test/old_tests/UnitTests/IInspectable_GetRuntimeClassName.cpp
test/old_tests/UnitTests/constexpr.cpp
test/old_tests/UnitTests/produce.cpp

This tickles an edge case in the metadata-based marshaller. Use an empty string instead.

Runtime class name for bare IInspectable should not be "Object"

---

vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/ConsoleApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Desktop/WindowsApplication/WindowsApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

Instead of making the oldest toolset the default, make the newest toolset the default. This ensures that projects load correctly in future VS versions with a higher version number.

Make the v142 toolset the default.

---

vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

Setting this to empty prevents the use of Directory.Build.props to disable specific warnings solution-wide.

Project templates should not set DisableSpecificWarnings to empty.

---

cppwinrt/code_writers.h

Fixes #945. Given that the component headers already use this I don't think this would break C++/WinRT compatibility with compilers that don't support this (technically it's non-standard). 
Question is if we need to keep the open file guard?

Add #pragma once in addition to header guard.

---

strings/base_agile_ref.h
strings/base_weak_ref.h
test/old_tests/UnitTests/weak.cpp
test/test/agile_ref.cpp

This allows you to create agile and weak references to com_ptr much more conveniently. Given declarations
```cpp
Uri uri;
com_ptr<::IPersist> persist;
```
| Try this              | or this              | Before | After    |
|-----------------------|----------------------|--------|----------|
| `agile_ref(uri)`      | `weak_ref(uri)`      | Fail   | Works    |
| `make_agile(uri)`     | `make_weak(uri)`     | Works  | Works    |
| `agile_ref(persist)`  | `weak_ref(persist)`  | Fail   | Works    |
| `make_agile(persist)` | `make_weak(persist)` | Fail   | Works    |
With the addition of the deduction guides, `make_agile` and `make_weak` are now superfluous, but we keep them around for backward compatibility.

Add deduction guides for agile_ref and weak_ref

---

strings/base_implements.h

A common error is forgetting to provide the name of the derived class as the first `implements<>` template parameter. This results in a strange `'implements_type' is not a member of any direct or indirect base class of 'MyClass'` error. Detect this case with a `static_assert` with a more help error message.
Note that we have to put the `static_assert` inside the implementation of `GetRuntimeClassName` rather than putting it in the class definition of `implements`. That's because `implements` is sometimes used with an incomplete type, and we cannot use `is_base_of` with incomplete types. Wait until `GetRuntimeClassName` is generated, at which point the class is complete.

Improve diagnostics when implements<> is used incorectly

---

cppwinrt/code_writers.h
strings/base_abi.h
test/test/memory_buffer.cpp
test/test/test.vcxproj

This adds a new `data()` method to get the data pointer returned by the `IMemoryBufferByteAccess::GetBuffer()` method for `Windows.Foundation.IMemoryBufferReference`.
Fixes #944.

Add IMemoryBufferByteAccess accessor

---

strings/base_reference_produce.h
strings/base_reference_produce_1.h
test/test_component_no_pch/test_component_no_pch.idl

Implementation relies on methods in the top-level header, so defer implementation to there.
This reverts the change to base_reference_produce.h from #906 and reduces base_reference_produce_1.h to merely forward references. This is enough to get structures to compile, although you cannot meaningfully use any IReferences in them until you include Windows.Foundation.h (which is consistent with existing rules for namespace headers).

IReference operators in level-1 header should be forward declarations

---

strings/base_delegate.h
test/test/delegate.cpp

Missing `return` statement prevented creation of delegates with non-void return value from a function pointer or raw pointer + member function pointer.

Fix delegates with return value passed as fptr or {p,mfptr}

---

strings/base_error.h
strings/base_meta.h
test/old_tests/UnitTests/hresult_error.cpp

Like `check_pointer`, `check_hresult` accepts multiple successful values. The `check_pointer` function returns the successful pointer, but `check_hresult` swallows the successful result, which makes using `check_hresult` inconvenient to use with COM methods that return `S_FALSE`. For example:
```cpp
if (hresult error = root->SelectSingleNode(query, node.put()); check_hresult(error), error == S_OK)
{
process(node);
}
```
Extending `check_hresult` to return the successful `hresult` simplifies the code:
```cpp
if (check_hresult(root->SelectSingleNode(query, node.put())) == S_OK)
{
process(node);
}
```
I think it is unlikely that anybody has been doing `decltype(check_hresult())`, so changing the return value should be non-breaking.

check_hresult returns the hresult as a convenience

---

vsix/Standalone/source.extension.vsixmanifest
vsix/packages.config
vsix/vsix.csproj

This updates the VSIX to work with Dev17 (VS 2022) Preview.
One thing I learned is that the VCTargets install path was deprecated starting in VS2019, so I had to update it to an explicit path under MSBuild.
See:
- https://docs.microsoft.com/en-us/visualstudio/extensibility/set-install-root?view=vs-2019
- https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-visual-cpp-overview?view=msvc-160
The second link suggests that the new path won't work in VS2017, and I thought we didn't still support VS2017, so I've moved up the minimum VS version from 2017 to 2019.

Update VSIX to work with Dev17

---

nuget/Microsoft.Windows.CppWinRT.targets
test/nuget/TestApp/TestApp.vcxproj
test/nuget/TestRuntimeComponent1/TestRuntimeComponent1.vcxproj
test/nuget/TestRuntimeComponent2/TestRuntimeComponent2.vcxproj
test/nuget/TestRuntimeComponent3/TestRuntimeComponent3.vcxproj
test/nuget/TestRuntimeComponentEmpty/TestRuntimeComponentEmpty.vcxproj

Current C++/WinRT override the GetResolvedWinMD target. However if the import order changes this override can easily break, like it does when NuGet imports the targets as part of PackageReference. 
This PR removes the override.
Validation:

Fix target override as it doesn't work when the target import order changes.

---

nuget/Microsoft.Windows.CppWinRT.props

When NuGet imports the props as part of PackageReference, it easy to end up in situations where the project file defines XamlLanguage before the C++/WinRT props are imported.
We shouldn't override if the value is already set.

Ensure we don't override XamlLanguage if it's already set.

---

nuget/Microsoft.Windows.CppWinRT.targets

#977 removed an override of a built-in CX target that wasn't working reliably. Because of this, various targets to resolve the WinMD would no longer find the WinMD file. This never worked reliably but it turns out the Xaml designer uses one of these targets. This PR adds a BeforeTargets to ensure the WinMD will be resolved.
Fixes #981
Verified that the test solution builds and the designer works as well.

Ensure the Xaml designer can find out WinMD

---

strings/base_com_ptr.h
strings/base_handle.h

The `put_abi` functions are already hardened in this way.

Harden `put` functions against misuse

---

vsix/Component/source.extension.vsixmanifest

This will help prevent [this error](https://developercommunity.visualstudio.com/t/Unable-to-update-from-Preview-11-to-Pre/1476321) from happening in the future. #960 should be fully working after this.

Fix cyclic dependency error when upgrading VS 2022

---

vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/ConsoleApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Desktop/WindowsApplication/WindowsApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

Visual Studio 2022 introduces a new toolset version, so we should use it for increased standards compliance and new features (also the v142 toolset isn't installed by default).

Use v143 toolset on VS 2022

---

strings/base_types.h
test/test/guid.cpp
test/test/test.vcxproj

Make `winrt::guid("...")` more useful at runtime by throwing on failure instead of aborting the program. See #991

Use throw rather than abort() for guid parse failures

---

strings/base_coroutine_foundation.h

Some uses of `co_await` were not protected by `WINRT_IMPL_COROUTINES`

---

cppwinrt/code_writers.h
test/test_component/test_component.idl

The previous testing didn't cover delegates.

Fix edge case in nested Windows namespace 

---

.gitignore
run_tests.cmd
test/old_tests/UnitTests/Main.cpp
test/test/main.cpp
test/test_win7/main.cpp

Fixes #1010 by calling Catch2's `reportFatal()` in the `std::terminate` handler so that failure logging is generated before the process exits.

Generate test failure output on abnormal termination

---

nuget/CppWinrtRules.Project.xml
nuget/Microsoft.Windows.CppWinRT.targets

/await:strict is binary compatible with c++20 coroutines. Instead of adding new logic to the C++/WinRT build targets, allow opt-out of the current default so users can set this manually.
For details, see: https://docs.microsoft.com/en-us/cpp/build/reference/await-enable-coroutine-support?view=msvc-160 and https://devblogs.microsoft.com/cppblog/cpp20-coroutine-improvements-in-visual-studio-2019-version-16-11/
Fixes #1014

Enable /await opt-out so users can manually enable /await:strict.

---

strings/base_collections_vector.h
test/test/observable_index_of.cpp
test/test/test.vcxproj

Avoid exception in observable IndexOf implementation

---

nuget/Microsoft.Windows.CppWinRT.targets

Without this, cppwinrt would attempt to use the output of MIDL files which where excluded from the build, resuting in mdmerge either erroring due to missing files, or using partially outdated build output.

Ignore MIDL files which are excluded from the build

---

strings/base_implements.h
strings/base_macros.h
strings/base_meta.h
strings/base_reference_produce.h
strings/base_types.h
strings/base_windows.h
test/test/guid.cpp
test/test_component_derived/pch.h

Before this change, if you tried to use classic COM without first including <unknwn.h>, C++/WinRT spit out really confusing error messages like
```cpp
auto widget = object.as<::IClassicComInterface>();
```
> error: 'unbox_value_type': no matching overloaded function found
or worse: Just ignored you!
```cpp
struct Widget : WidgetT<Widget, ::IPersistStream>
{
// IPersistStream is simply ignored!
};
```
This change relaxes the rules around `<unknwn.h>` and improves diagnostics.
1. If you want to use `com_ptr<I>`, `as<I>`, etc. with classic COM interfaces, you need only include `<unknwn.h>` at *some point* before using them. Doesn't have to be included before `winrt/base.h`. (And really, since you need to include `<unknwn.h>` in order to define *any* classic COM interfaces, the prerequisite …

Improve classic COM support, and improve diagnostic for common error

---

strings/base_activation.h
test/test_module_lock_none/main.cpp

C++/WinRT provides `WINRT_NO_MODULE_LOCK` that may be used by apps or pinned DLLs (that don't support unloading) to avoid the overhead of tracking of a module reference count. This update further optimizes the factory cache in such cases since unloading has an impact on caching performance. With this change, C++/WinRT is on par with [the Rust language](https://github.com/microsoft/windows-rs). Previously, Rust was just slightly faster. 
Data from: https://github.com/kennykerr/lang-perf
cc @axelandrejs

Optimize factory caching for apps and pinned DLLs

---

cppwinrt/code_writers.h
test/test/optional.cpp
test/test/test.vcxproj
test/test_component/Optional.cpp
test/test_component/Optional.h
test/test_component/test_component.idl
test/test_component/test_component.vcxproj

Support binding `std::optional<T>` implementation to `IReference<T>` parameters

---

cppwinrt.sln
strings/base_agile_ref.h
test/test_component_base/pch.h
test/test_module_lock_none/main.cpp

I also noticed that this combination had no test.

Simplify use of `WINRT_NO_MODULE_LOCK` in DLLs

---

strings/base_natvis.h

If you pass `-DWINRT_NATVIS` to the compiler (to force natvis support even in retail builds), it defines the preprocessor symbol to `1`, as if you had written
```cpp
#define WINRT_NATVIS 1
```
This causes debug builds to generate a macro redefinition warning because the debug build force-defines `WINRT_NATVIS` as the empty macro.
We don't really care what it defined to, as long as it's defined. Guard the redefinition to avoid the spurious warning.

Avoid spurious WINRT_NATVIS redefinition warning

---

cppwinrt/component_writers.h
test/test_component/Class.h
test/test_component/test_component.idl

Allow non-void static setter methods when compiling with `-opt`

---

test/nuget/TestRuntimeComponentNamespaceUnderscore/TestRuntimeComponentNamespaceUnderscore.vcxproj
test/nuget/TestStaticLibrary7/TestStaticLibrary7.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

these disable an important diagnostic and have not been needed for a long time as the Xaml Compiler was fixed a few years ago.

remove WINRT_NO_MAKE_DETECTION from project templates

---

cppwinrt/code_writers.h
cppwinrt/cppwinrt.vcxproj
cppwinrt/cppwinrt.vcxproj.filters
strings/base_stringable_format.h
strings/base_stringable_format_1.h

Fixes #1069
Was manually tested by building and running this snippet:
```cpp
// silence a clang coroutine warning caused by cppwinrt. we don't actually use coroutines here.
#define _SILENCE_CLANG_COROUTINE_MESSAGE
// std::format is hidden behind /std:c++latest due to ABI concerns right now
// but the headers don't detect Clang's -std=c++2b, so manually have them believe we are using C++23.
#define _HAS_CXX23 1
#include <format>
#include <iostream>
// required for cppwinrt to not fail building with clang
#include <guiddef.h>
#include "winrt/Windows.Foundation.h"
#pragma comment(lib, "onecore.lib")
struct stringable : winrt::implements<stringable, winrt::Windows::Foundation::IStringable>
{
winrt::hstring ToString()
{
return L"a stringable object";
}
};
int main()
{ …
```

Fix compilation under Clang

---

natvis/cppwinrt.natvis

Make it look more like a Color value:
\# 7F 80 80 40

Add visualizer for winrt::Windows::UI::Color

---

strings/base_implements.h
test/old_tests/UnitTests/weak.cpp

`root_implements::NonDelegatingRelease` sets `m_references = 1` prior to initiating destruction so that the destructor sees a nonzero reference count. As a side effect, it also breaks the connection to the weak reference control block.
`~root_implements` performs a bonus `subtract_reference` to clean up any weak reference control block that may have re-materialized during destruction. The extra decrement is safe because we set `m_references = 1` earlier.
However, if the `root_implements::Release` was overriden by a derived class, the derived class's `Release` may not do the same `m_references = 1` trick, and then the bonus decrement in the destructor will decrement below zero.
Who would override `root_implements::Release`? `promise_base`, that's who. As a result, a weak reference to a …

Fix weak references to coroutines

---

test/test_win7/pch.h

Add a missing 'typename' keyword in "test_win7\pch.h" to fix the following error.
`F:\gitP\microsoft\cppwinrt\test\test_win7\pch.h(45,50): error C2923: 'std::is_same_v': 'async_traits<winrt::Windows::Foundation::IAsyncOperation<int>>::progress_type' is not a valid template type argument for parameter '<unnamed-symbol>' `

Add a missing 'typename' keyword in "test_win7\pch.h"

---

cppwinrt/type_writers.h
test/test/rational.cpp
test/test/test.vcxproj
test/test_component/Simple.h
test/test_component/test_component.idl

Unfortunately someone added `Rational` without informing language projections, so it got caught in the Numerics net. Refine the Numerics namespace special-handling to transform only the types that need transforming.
Fixes #1105

Add type support for `Windows.Foundation.Numerics.Rational`

---

strings/base_implements.h
test/old_tests/UnitTests/weak.cpp

Turns out that `IWeakReference` does work for classic COM: Even though the output pointer of `IWeakReference::Resolve` is typed as `IInspectable**`, it is annotated as `iid_is(riid)`, so COM ignores the formal type and relies on the IID, which is not constrained to derive from IInspectable. Verified that the COM marshaling metadata for the Resolve method is unaffected by the formal type of the output pointer. In particular, querying the resulting object for `IInspectable` will send a request over the wire (if never requested before), proving the COM did not infer `IInspectable` support.
This is a behavior change: Previously, pure classic COM objects did not support weak references. However, it removes developer surprise, since they see a method called `get_weak()` and expect it to work. …

Extend weak reference support to classic COM

---

strings/base_types.h
test/test/guid.cpp

Support the format returned by StringFromGUID2 in guid.parse. ```{(})```  are common characters used in guid formats and it would be convenient if cppwinrt would automatically handle them.

Support the format returned by StringFromGUID2 in guid.parse.

---

strings/base_chrono.h

Attempting to compile the [example code](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#can-i-use-llvm-clang-to-compile-with-c---winrt-) in C++/WinRT FAQ with Clang (LLVM 14) and C++/WinRT 2.0.220224.4 results in the following compilation error:
```
winrt/base.h(8272,77): error: no viable conversion from 'time_point<[...], duration<[...], ratio<[...], __static_lcm<ratio<1, 10000000>::den, ratio<1, 1>::den>::value aka 10000000>>>' to 'const time_point<[...], duration<[...], ratio<[...], 1000000>>>'
return static_cast<time_t>(std::chrono::system_clock::to_time_t(to_sys(time)));
^~~~~~~~~~~~
```
This originates from the fact that `system_clock` uses [microseconds in libc++](https://github.com/llvm/llvm-project/blob/3e6cfc631b816144d1ddfb4bb9f84af43367835c/libcxx/include/_ …

Fix time_point compilation error with Clang

---

cppwinrt/code_writers.h
strings/base_macros.h

This macro was added as a workaround (#433) to avoid an IntelliSense bug that has long since been fixed.

Remove `WINRT_IMPL_AUTO`

---

cppwinrt/code_writers.h

Remove workaround for [this Visual C++ code gen bug](https://developercommunity.visualstudio.com/content/problem/554130/incorrect-code-gen-when-invoking-a-conversion-oper.html).
Closes #1115

Remove workaround for Visual C++ code gen bug

---

Directory.Build.Props
Directory.Build.Targets
build_test_all.cmd
cppwinrt/cppwinrt.vcxproj
natvis/cppwinrtvisualizer.vcxproj
prebuild/prebuild.vcxproj
scratch/scratch.vcxproj
test/Directory.Build.Props
test/old_tests/Component/Component.vcxproj
test/old_tests/Composable/Composable.vcxproj
test/old_tests/UnitTests/Tests.vcxproj
test/test/test.vcxproj
test/test_component/test_component.vcxproj
test/test_component_base/test_component_base.vcxproj
test/test_component_derived/test_component_derived.vcxproj
test/test_component_fast/test_component_fast.vcxproj
test/test_component_folders/test_component_folders.vcxproj
test/test_component_no_pch/test_component_no_pch.vcxproj
test/test_cpp20/test_cpp20.vcxproj
test/test_fast/test_fast.vcxproj
test/test_fast_fwd/test_fast_fwd.vcxproj
test/test_module_lock_custom/test_module_lock_custom.vcxproj
test/test_module_lock_none/test_module_lock_none.vcxproj
test/test_slow/test_slow.vcxproj
test/test_win7/test_win7.vcxproj

Looked at latest version of catch, 2.13.8, and saw no significant differences from 2.13.7 (checked in here) to suggest that would help.  So backing test collateral off to platform toolset v142 (VS1029) to unblock build for now.

catch is evidently incompatible with VS 2022 (platform toolset v143) - backing off to unblock

---

natvis/object_visualizer.cpp

per advice from the VSSDK team, made sure GetChildren returns requested items, not just relying on GetItems.  (this lazy technique worked for VS2017, but does not with VS2019+)

fix regression in nested visualizations with VS2019+

---

natvis/cppwinrt.natvis
natvis/cppwinrt_visualizer.cpp
natvis/object_visualizer.cpp
natvis/object_visualizer.h

Added visualization for winrt::impl::producer<...> subclasses (implementations), per several requests
Always show raw data, for classes that inherit IInspectable but metadata is not available

Provide implementation-side visualization (per request), and always show raw data

---

cppwinrt/component_writers.h
nuget/readme.md
strings/base_implements.h
test/test/initialize.cpp
test/test/initialize_instance.cpp
test/test/test.vcxproj
vsix/ItemTemplates/BlankPage/BlankPage.cpp
vsix/ItemTemplates/BlankPage/BlankPage.h
vsix/ItemTemplates/BlankUserControl/BlankUserControl.cpp
vsix/ItemTemplates/BlankUserControl/BlankUserControl.h
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/App.cpp
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/App.h
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/MainPage.cpp
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/MainPage.h

Initialization routines for components are now called after construction, rather than during.  This prevents 'this' pointers from being handed out and retained during construction, leading to multiple destructor calls.  If a component has an initialize_instance function (hopefully ugly enough named to prevent need for opting out), member or free (so that the Xaml compiler doesn't require a coordinated fix), then this function is called after the implementation is completely constructed.  If the initializer throws, the instance is destructed and the exception propagates as before.  Existing code can now remove InitializeComponent calls from class constructors, or override in order to access Xaml properties after initialization.  The support is general - non-Xaml code can also define …

two-phase initialization support to prevent double-destruction on handing out this pointer in ctor

---

cppwinrt/helpers.h
test/test_component_fast/Nomadic.cpp
test/test_component_fast/Nomadic.h
test/test_component_fast/test_component_fast.idl
test/test_component_fast/test_component_fast.vcxproj
test/test_fast/Nomadic.cpp
test/test_fast/test_fast.vcxproj

Currently interfaces are being sorted for fast ABI by their current contract version which is incorrect because (1) we actually want to consider their initial contract/version, not the current ones, and (2) we want to consider the contract each interface was introduced in relative to the contract history of the type they apply to. E.g. an interface introduced in contract 'A' version 2 should be sorted before an interface introduced in contract 'B' version 1 if the class was in contract 'A' before contract 'B'.
Note that the sorting algorithm is N^2, however this should be fine since moving contracts should be rare and the history should be small to the point that trying to create a graph/linked list would be wasteful and probably more inefficient.
Also note that this maintains some …

Update C++/WinRT to consider the full contract version history for fast ABI

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h

We forgot to apply the `auto` trick to `auto_revoke` methods to catch missing header files at compile time. As a result, people who used `auto_revoke` didn't learn about missing header files until link time.
Apply the same technique to auto-revoke event handler registration.
(Story time: A customer was running into linker errors due to a missing header file when they used `auto_revoke`. One thing they tried was switching to non-`auto_revoke` events, and then they got the compile-time error. But their conclusion wasn't "Oh, that's my problem" but rather "Oh no, that made it worse, go back!")

Use `auto` trick to catch missing header files for auto_revoke

---

cppwinrt/cmd_reader.h

This change fixes #1145 by testing whether an `SDKManifest.xml` exists within an Extension SDK's folder before attempting to read it, and ignores Extension SDKs which lack this file.

Test whether SDKManifest.xml exists before attempting to read it.

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
cppwinrt/cppwinrt.vcxproj
cppwinrt/cppwinrt.vcxproj.filters
nuget/readme.md
strings/base_implements.h
strings/base_xaml_component_connector.h

fixes #1140
This change adds a helper, ComponentConnectorT, to resolve the breaking change introduced with #1140.  Note that this is manual opt-in for the developer, and not an automatic fix, as that would require coordinated work with the Xaml Compiler.  I don't think it's worth the effort to do that, for several reasons:
When deriving from a base class with markup, IComponentConnector::Connect has never been reliable outside construction, such as when called back from FindName.  If a base class has a property with both the same type (e.g., TextBlock) and connectionId as a derived class,  then Connect would erroneously call the derived property setter.   The same risk applies to DisconnectUnloadedObject.  This was the opposite of the non-virtual dispatch that InitializeComponent was …

Add support for composed implementations of IComponentConnector

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
test/test_component/Class.cpp

The same way we don't use the auto trick for static properties and static methods.
Fixes issue introduced by #1136

Static events should not use the auto trick

---

nuget/readme.md

Just adds a small paragraph to readme.md clarifying how to use `ComponentConnectorT`.
This is an easy mistake to make since the snippet just above suggests people should call ClassT::InitializeComponent all the time.

Clarify usage of ComponentConnectorT::InitializeComponent

---

cppwinrt/file_writers.h
test/test/names.cpp

Project contract names so they can be passed to IsApiContractPresent.

Add `name_of<>` support to contracts

---

strings/base_meta.h

If GUID is not defined, then don't breathe the name of the `__uuidof` intrinsic, because that would instantiate an undefined structure. clang is stricter about this than msvc, but fix both just in case.
Fixes #1179

Don't use __uuidof without GUID

---

strings/base_string.h

Static code analysis flagged these three instances of signed/unsigned mismatches. This change adds explicit static_cast to uint32_t to indicate that this is intentional.

Add explicit casts to atomic_ref_count

---

Directory.Build.Props
natvis/cppwinrtvisualizer.vcxproj
strings/base_identity.h
strings/base_meta.h
test/test/generic_types.cpp
test/test_win7/generic_types.cpp

This makes `guid_v` (and by extension `name_v`) constexpr on Clang, improves the error reporting when `unknwn.h` is not included before `winrt/base.h` (gives a compile-time error instead of an empty GUID and potential ODR violations), and finally brings back the ability to use classic COM without including `unknwn.h` before `winrt/base.h` on MSVC.
Fixes #1186

Make guid constexpr on clang, improve error reporting

---

strings/base_meta.h

Also, enable fast path for Clang and give friendlier errors to MSVC.
Testing the `__has_declspec_attribute` path revealed to be a bit tricky, because a bunch of CRT headers rely on MS extensions. I ended up passing `-fno-declspec` to disable `__declspec` specifically and then adding `#define __declspec(x)` to no-op all the `__declspec` in the CRT headers and cppwinrt. This finally gave the desired error:
```
_build\x64\Debug\winrt/base.h(688,9): error: static_assert failed due to requirement 'std::is_void_v<IClassFactory>' "To use classic COM interfaces, you must compile with -fms-extensions."
static_assert(std::is_void_v<T> /* dependent_false */, "To use classic COM interfaces, you must compile with -fms-extensions.");
^             ~~~~~~~~~~~~~~~~~
```

Fix classic COM errors on non-supported compilers

---

cppwinrt/cmd_reader.h
cppwinrt/code_writers.h
cppwinrt/component_writers.h
cppwinrt/helpers.h
cppwinrt/text_writer.h
natvis/cppwinrt_visualizer.cpp
natvis/object_visualizer.cpp
prebuild/main.cpp
strings/base_collections_input_vector.h
strings/base_coroutine_foundation.h
strings/base_implements.h
test/old_tests/UnitTests/handle.cpp

Mostly dealing with initialization and codestyle.

Fix Clang-15 warnings

---

cppwinrt/code_writers.h
cppwinrt/component_writers.h
strings/base_abi.h
strings/base_composable.h
strings/base_delegate.h
strings/base_error.h
strings/base_extern.h
strings/base_fast_forward.h
strings/base_implements.h
strings/base_includes.h
strings/base_macros.h
strings/base_meta.h

This aims to make the generated headers usable by a Clang-based mingw-w64 toolchain. See https://github.com/mstorsjo/llvm-mingw/issues/307
Note that, even with these changes, the headers does not work with llvm-mingw 15 out of the box, because there are some functions and definitions missing in mingw-w64's version of `intrin.h`. We will consider fixing this upstream.

Improve compatibility with mingw-w64 in generated headers

---

.github/workflows/msvc.yml
.gitignore
run_tests.cmd

This is *not* intended to be a replacement to the Azure build, but as a supplemental build. The added workflow performs builds and runs tests on x86 and x64, and also tries to build the nuget package.

Add GitHub Action build and test workflow

---

.github/workflows/ci.yml
test/old_tests/UnitTests/Errors.cpp
test/old_tests/UnitTests/array.cpp
test/old_tests/UnitTests/async.cpp
test/old_tests/UnitTests/hresult_error.cpp
test/test/async_auto_cancel.cpp
test/test/async_cancel_callback.cpp
test/test/async_check_cancel.cpp
test/test/async_ref_result.cpp
test/test/error_info.cpp
test/test/hresult_class_not_registered.cpp
test/test/multi_threaded_map.cpp
test/test/notify_awaiter.cpp
test/test/when.cpp
test/test_cpp20/main.cpp
test/test_fast/main.cpp
test/test_fast_fwd/main.cpp
test/test_module_lock_custom/main.cpp
test/test_module_lock_none/main.cpp
test/test_slow/main.cpp
test/test_win7/async_auto_cancel.cpp
test/test_win7/async_cancel_callback.cpp
test/test_win7/async_check_cancel.cpp

This PR contains some of the changes that will help adding the Clang CI (#1203) but are more about general fixes which are not specific to Clang.

Various fixes for tests/CI

---

.github/workflows/ci.yml
Directory.Build.Props
test/old_tests/UnitTests/Main.cpp
test/test/disconnected.cpp
test/test/main.cpp
test/test_cpp20/main.cpp
test/test_fast/main.cpp
test/test_fast_fwd/main.cpp
test/test_module_lock_custom/main.cpp
test/test_module_lock_none/main.cpp
test/test_slow/main.cpp
test/test_win7/disconnected.cpp
test/test_win7/main.cpp

This basically rewrites the CI jobs based on the original `build_test_all.cmd` but split the steps into different jobs so any failures will be easier to pinpoint. This also allows the tests to be built and run in parallel, which can save about 5 minutes of full run time.
One thing to note is that the nuget test build seems to be failing even on the initial GHA workflow. This failure was hidden before because `build_test_all.cmd` did not detect the build error. Now that it is exposed, I have added a hack to purposely ignore the failure (instead only emit a warning) because I don't know how to fix it properly.

Improve CI jobs split

---

.github/workflows/ci.yml
cppwinrt/cppwinrt.vcxproj
test/old_tests/UnitTests/agile_ref.cpp
test/old_tests/UnitTests/apartment_context.cpp
test/old_tests/UnitTests/async.cpp
test/old_tests/UnitTests/async_cancel.cpp
test/old_tests/UnitTests/weak.cpp
test/test/GetMany.cpp
test/test/async_auto_cancel.cpp
test/test/async_cancel_callback.cpp
test/test/async_check_cancel.cpp
test/test/async_propagate_cancel.cpp
test/test/async_throw.cpp
test/test/async_wait_for.cpp
test/test/await_adapter.cpp
test/test/coro_system.cpp
test/test/coro_ui_core.cpp
test/test/custom_error.cpp
test/test/disconnected.cpp
test/test/multi_threaded_map.cpp
test/test/multi_threaded_vector.cpp
test/test_cpp20/custom_error.cpp
test/test_win7/GetMany.cpp
test/test_win7/async_auto_cancel.cpp
test/test_win7/async_cancel_callback.cpp
test/test_win7/async_check_cancel.cpp
test/test_win7/async_throw.cpp
test/test_win7/async_wait_for.cpp
test/test_win7/disconnected.cpp

Some fixes and workarounds are needed to get Clang to build some of the tests. There are still some outstanding issues:
* For both `test\test\GetMany.cpp` and `test\test_win7\GetMany.cpp`, we get a recursive template instantiation:
```
In file included from GetMany.cpp:1:
In file included from D:\a\cppwinrt\cppwinrt\test\test\pch.cpp:1:
In file included from ./pch.h:7:
In file included from D:\a\cppwinrt\cppwinrt\_build\x64\Release\winrt\Windows.Foundation.Collections.h:6:
In file included from D:\a\cppwinrt\cppwinrt\_build\x64\Release\winrt\base.h:10:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include\algorithm:11:
In file included from C:\Program Files\Microsoft Visual …
```

Add CI test with LLVM 15 clang-cl

---

strings/base_activation.h

There are still some intrinsics and defines missing in mingw-w64 (see https://github.com/mstorsjo/llvm-mingw/issues/307) which can all be replaced with other compatible constructions. Verified by compiling a sample program locally for i686, x86_64 and aarch64 (aarch64 build is untested because I don't have a compatible system).
(CI checks for mingw-w64 will be coming soon™)
CC: @mstorsjo @cristianadam

Better support for mingw-w64 and GCC-compatible compilers

---

strings/base_macros.h
strings/base_meta.h

Mingw-w64 does not use `__declspec(uuid(x))` but has its own way of supporting `__uuidof` by defining UUIDs with a special macro `__CRT_UUID_DECL`, which does actually work here.

Enable classic COM on mingw-w64

---

strings/base_xaml_component_connector.h

Discovered with WinUI-PR pipeline run: update versions for CppWinRT, wil, BuildTools, .NET runtime

Projects with a nested Windows namespace (e.g., Microsoft::Windows) fail to compile

---

strings/base_xaml_component_connector_winui.h

The other half of this change:
https://github.com/microsoft/cppwinrt/pull/1223

Include WinUI too for fully qualified namespace fix (sigh) 

---

.github/workflows/ci.yml
cppwinrt/cmd_reader.h
strings/base_includes.h
strings/base_macros.h
test/CMakeLists.txt
test/old_tests/CMakeLists.txt
test/old_tests/UnitTests/CMakeLists.txt
test/old_tests/UnitTests/Main.cpp
test/old_tests/UnitTests/VariadicDelegate.cpp
test/old_tests/UnitTests/agile_ref.cpp
test/old_tests/UnitTests/apartment_context.cpp
test/old_tests/UnitTests/array.cpp
test/old_tests/UnitTests/async.cpp
test/old_tests/UnitTests/async_cancel.cpp
test/old_tests/UnitTests/capture.cpp
test/old_tests/UnitTests/com_ref.cpp
test/old_tests/UnitTests/hresult_error.cpp
test/old_tests/UnitTests/make_self.cpp
test/old_tests/UnitTests/param_iterable.cpp
test/old_tests/UnitTests/pch.h
test/test/coro_system.cpp
test/test/coro_ui_core.cpp
test/test/main.cpp
test/test_cpp20/CMakeLists.txt
test/test_cpp20/main.cpp
test/test_win7/async_auto_cancel.cpp
test/test_win7/async_cancel_callback.cpp
test/test_win7/async_check_cancel.cpp
test/test_win7/async_throw.cpp
test/test_win7/async_wait_for.cpp

Changes include:
- Since a partial `windowsnumerics.impl.h` header has been added to mingw-w64 recently, we can enable the tests that depend on it. If it is not available in the current mingw-w64 toolchain, there is an option to download a copy of it from the mingw-w64 git repo to allow these tests to run.
- Enable some test cases of `test_cpp20` and `test_old` for llvm-mingw. `test_old` in particular depends on `windowsnumerics.impl.h`)
- Re-enable test code for Clang fixed by #1228.
- Enable some test cases for llvm-mingw that crashes only when built using Clang with MSVC ABI.
- Make some tests relying on error messages pass on non-English Windows systems.
- Use lowercase filename when including Windows headers, which is needed for cross-building from Linux with mingw-w64.

Enable more tests on llvm-mingw and some fixes

---

strings/base_string.h
test/test_cpp20/format.cpp

With std::format reference semantics are only used for user defined types so without std::forward you somehow can't format integers. Forwarding twice is safe because objects are not copied/moved from during formatting.
Would like a quick release of this fix because it's breaking my scenario.

Fix formatting primitive types such as integers

---

test/test/CMakeLists.txt
test/test/multi_threaded_common.h
test/test/multi_threaded_map.cpp
test/test/multi_threaded_vector.cpp

Removed one bit of enable_if_t metaprogramming that doesn't build with Clang and seems to be unneeded. The error message is:
```
enable_if.h:26:78: error: no type named 'type' in 'std::enable_if<false>'; 'enable_if' cannot be used to disable this declaration
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
^~~
multi_threaded_common.h:155:34: note: in instantiation of template type alias 'enable_if_t' requested here
template<typename = std::enable_if_t<!std::is_same_v<ConvertibleFrom, void>>>
^
[snip]
```

Fix multi_threaded_map/_vector tests on Clang

---

.github/workflows/ci.yml
strings/base_weak_ref.h
test/CMakeLists.txt
test/catch.hpp
test/test_cpp20/CMakeLists.txt

There was a null pointer dereference bug in `weak_ref::get()`. This happens to not cause any issues with MSVC, but does crash with MinGW ABI when built with optimizations, because a cast in `winrt::get_self` would adjust the (null) pointer by an offset due to the different vtable layout, which ends up escaping null checks.
I didn't notice this earlier because all my tests happen to be unoptimized Debug builds. I tracked down this bug with the help of UBSan.
Because of this, I have also enabled Release build checks for llvm-mingw, and enabled ASan+UBSan for the tests in Debug builds.

Fix null pointer dereference in weak_ref::get()

---

cppwinrt/pch.h
cppwinrt/text_writer.h
strings/base_chrono.h
strings/base_includes.h
strings/base_string_operators.h

**Generated headers do not actually work on GCC.**
This implements some changes intended to improve compatibility with GCC 12. However, there is an [8-year-old upstream defect](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61663) which stops `winrt::impl::bind_in` from compiling:
<details>
<summary>GCC 12 Compile Error</summary>
```
In file included from C:/msys64/home/Alvin/cppwinrt/test/cppwinrt/winrt/Windows.Foundation.Collections.h:9,
from D:/cppwinrt/test/test/pch.h:9,
from C:/msys64/home/Alvin/cppwinrt/test/test/CMakeFiles/test-vanilla.dir/cmake_pch.hxx:5,
from <command-line>:
C:/msys64/home/Alvin/cppwinrt/test/cppwinrt/winrt/Windows.Foundation.h: In instantiation of 'auto winrt::impl::consume_Windows_Foundation_IPropertyValueStatics<D>::CreateGuid(const winrt::guid&) const [with D = …
```

Partial GCC compatibility improvements

---

test/CMakeLists.txt
test/test_cpp20/format.cpp
test/test_cpp20/ranges.cpp

Tested locally with llvm-mingw nightly build (LLVM 169f0556530412ed1589ba5f3edeb8665bf16a91, mingw-w64 af82412710326734249c374cd3e182ffc6dce09a). This also fixes build error of test_cpp20/format.cpp with libc++ >=15.0.1

Fix llvm-mingw tests with LLVM trunk

---

.github/actions/setup-llvm-mingw/action.yml
.github/actions/setup-llvm-msvc/action.yml
.github/workflows/ci.yml

I extracted the LLVM setup steps into composite actions and enabled caching the LLVM toolchains. The clang-cl jobs are perhaps slightly faster now but not a significant difference.

CI: Refactor LLVM setup steps and use cache

---

.github/workflows/ci.yml
CMakeLists.txt
strings/base_chrono.h
strings/base_coroutine_threadpool.h
strings/base_extern.h
strings/base_includes.h
strings/base_string.h
test/CMakeLists.txt
test/old_tests/UnitTests/CMakeLists.txt
test/old_tests/UnitTests/agile_ref.cpp
test/old_tests/UnitTests/async.cpp
test/old_tests/UnitTests/hstring.cpp
test/old_tests/UnitTests/weak.cpp
test/test/CMakeLists.txt
test/test/async_propagate_cancel.cpp
test/test/custom_error.cpp
test/test_cpp20/CMakeLists.txt
test/test_cpp20/custom_error.cpp
test/test_win7/CMakeLists.txt

Changes for GCC compatibility:
- Added GCC-only hack for `winrt::impl::bind_in` mentioned in https://github.com/microsoft/cppwinrt/pull/1234 (upstream: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61663)
- Fixed the `WINRT_IMPL_LINK` macro to properly declare the symbol as global (__GNUC__).
- Added GCC-only hack move constructors to the awaitables in `resume_after` and `resume_on_signal` because GCC adds useless moves in `co_await` (suspect to be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99575)
- ~~Added GCC-only hack copy constructor to `thread_pool` because GCC seems to want it when building the `thread_pool.cpp` test (suspect to be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103963)~~
- ~~Note that this also changes the `m_pool` field to be a `std::shared_ptr`.~~
- (reverted)
- …

Make compatible with GCC

---

test/old_tests/UnitTests/clock.cpp

This test fails intermittently but it's hard to tell what's wrong since the error report doesn't include the failing values. This just ensures that we can see the values when it fails and perhaps gain some more insight in the failure.

Improve error reporting for clock test

---

strings/base_coroutine_foundation.h
strings/base_coroutine_threadpool.h
test/test/async_propagate_cancel.cpp
test/test/await_completed.cpp

& make propagation tests more reliable at detecting future failures. Relying on a race proved to be not reliable, as shown by #1228 only causing intermittent failures instead of consistent ones.
Some notes:
- I made cancellable_awaiter use CRTP to avoid a virtual call to enable_cancellation, but this comes at the size of potential code size increase. Can easily revert to a virtual call to make cancellable_awaiter a non-template.
- I had to move the awaiters for resume_on_signal and resume_after to be outside of their respective functions, otherwise I could not make await_suspend a template.
- Are there any docs changes needed? I know this blog post will probably need one: https://devblogs.microsoft.com/oldnewthing/20200923-00/?p=104261
- I guess now everybody can make cancellable promises …

Fix cancellation propagation by moving responsability to awaiter

---

test/old_tests/UnitTests/clock.cpp

https://github.com/microsoft/cppwinrt/pull/1248#issuecomment-1356318850

Try to fix random failure of the clock test

---

strings/base_coroutine_foundation.h

The function make_delegate_with_shared_state (from strings/base_coroutine_foundation.h) uses on object after it was moved. 'd' is moved using std::move and then it's passed to get_abi. The usage of 'd' after it was moved it undefined.

Fix object usage after move in make_delegate_with_shared_state

---

strings/base_extern.h

Weak symbols on mingw-w64 target with GCC and the GNU linker is a bit broken for the intended use. When using the .weak + .set combo and the referenced symbol is undefined, LD does not produce an error but instead treat the referenced symbol like a weak symbol. This can happen if some of the link library flags is missing. The output executables will crash on run time, which can be very confusing.
This change makes the WINRT_IMPL_... Windows API declarations on GNUC use asm labels instead. This means we lose the ability to "hook" these functions when compiling for mingw-w64 target. But as mentioned in [#475], developers should not be doing this anyway.
[#475]: https://github.com/microsoft/cppwinrt/pull/475

mingw: Stop using .weak symbols aliases

---

CMakeLists.txt

When integrating cppwinrt from another project, I want to vendor the winmd headers into the source tree to avoid performing the download during build. This change adds a `EXTERNAL_WINMD_INCLUDE_DIR` variable to enable this usage.

cmake: Allow using external winmd headers to bypass download

---

strings/base_string.h

This works around a compile error due to the floating point version of `std::to_chars` not implemented in libc++ 13, so that C++/WinRT can be used on LLVM 13 with limited support. It should work as long as none of the functions involving coroutines are used.

Make headers partially usable with LLVM/libc++ 13

---

cppwinrt/code_writers.h
cppwinrt/main.cpp
cppwinrt/settings.h

The `-license` option now accepts an optional path argument, which can point to a text file to be used as the license text in the generated header files. The license text is automatically wrapped in a block of single-line comments.
Closes #1261

Add option for using custom license text

---

test/test_cpp20/custom_error.cpp

Tested with a recent llvm-mingw build very close to LLVM 16 rc1.
LLVM 16.0.0 should be releasing two months later. I will look into updating the CI after that.

tests: Fix and enable cpp20/custom_error for incoming LLVM 16

---

.pipelines/build.yml

Among other things, this will allow the C++/WinRT build pipeline to stay synchronized with the product code.
build.yaml contains the same build steps as the original classic pipeline. Here's a test run. https://microsoft.visualstudio.com/Dart/_build/results?buildId=63658741&view=results

Move build pipeline into YAML

---

strings/base_stringable_format.h
strings/base_stringable_format_1.h

Without this, `IStringable` and types which implement `IStringable` technically did not meet the [`formattable` concept](http://eel.is/c++draft/format.formattable), which uses a `const formatter<remove_cvref_t<T>, charT>` to verify for formattability.

Make the formatter for IStringable const

---

strings/base_implements.h

The issue is that the code analysis engine doesn't realize - it doesn't look at the implementation - that the pointer stored within the `com_ptr` is actually checked for validity before proceeding. 
Fixes #1267

Workaround for false positive code analysis warning

---

strings/base_coroutine_foundation.h
strings/base_coroutine_threadpool.h
test/test/await_completed.cpp
test/test_cpp20/await_completed.cpp

The big deal here is that we fix `co_await apartment_context` so that it consumes no stack[1] if you are already in the destination context. This is a big win for loops that do apartment switching.
To do this, `impl::resume_apartment` now returns `true` if it wants the caller to resume the coroutine synchronously, rather than doing it directly. If the caller is `await_suspend`, then it can propagate that result to the coroutine infrastructure and avoid stack build-up.
Fixed a lifetime issue in `apartment_awaiter`, which copied the context too soon. It needs to copy it in the `await_suspend`, because the coroutine is to resume synchronously in the new apartment, which under the old code would destruct the context while `await_suspend` was still using it. This shifts a refcount update from …

Stack usage reduction in apartment switching, and lifetime fixes

---

strings/base_coroutine_foundation.h
strings/base_coroutine_threadpool.h
test/test/await_completed.cpp

The old code would invoke the handle recursively. The new code returns `false` from `await_suspend`, allowing the calling coroutine to resume with no stack consumption. Use `[[nodiscard]]` to ensure I updated all callers, and to avoid future errors with new callers.
Also remove `#ifdef`s to work around code generation issues in MSVC versions less than 16.11. If you are on a version that old, you should stick with an older version of C++/WinRT.

Reduce stack consumption if unable to switch to apartment_context

---

test/old_tests/UnitTests/clock.cpp

The clock epoch tests are sensitive to CPU speed and the precise moment the clock ticks over from one second to another. Change the way we do epoch tests so that they are not affected by either factor.
This fixes a spurious CI test failure where the test environment was 3 milliseconds too slow.
https://github.com/oldnewthing/cppwinrt/actions/runs/4195918696/jobs/7276654213

Fix unreliable clock epoch tests

---

strings/base_implements.h
test/old_tests/UnitTests/as_implements.cpp

In Clang, the conversion from `producer_convert` to `const producer_ref<I>`
does not allow for the move-initialization of `I` via `I(I&&)` (implicit
or explicit) due to a language misspecification¹.
In brief², we cannot offer zero-cost initialization of projected types
from implementation types _in all meaningful cases_ in projects compiled
with clang.
Until it improves (which is tracked in llvm/llvm-project#17056), this
conversion operator will allow for C++/WinRT code to compile with Clang.
Closes #1273
¹ http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2077 documents
the language standard bug that results in this.
² In non-brief, https://stackoverflow.com/a/70654432

Add a clang-specific impl->projection conversion operator

---

.pipelines/sync-mirror.yml

This pipeline executes a series of git commands to fetch changes from a specified repo (defaults to this GitHub repo) and pulls those changes into a mirror repo.
This way we can have a mirror repo that contains the same revision history as our public repo, but we can automate the process of syncing it up to date.

Create pipeline to sync mirror repo

---

nuget/Microsoft.Windows.CppWinRT.props
nuget/Microsoft.Windows.CppWinRT.targets
test/nuget/NuGetTest.sln
test/nuget/TestApp/TestApp.vcxproj
test/nuget/TestProxyStub/IAsyncContract.idl
test/nuget/TestProxyStub/IAsyncContractParameter.idl
test/nuget/TestProxyStub/TestProxyStub.def
test/nuget/TestProxyStub/TestProxyStub.vcxproj
test/nuget/TestProxyStub/pch.cpp
test/nuget/TestProxyStub/pch.h

This change makes it easier to generate proxy stubs by allowing modern idl to generate proxy stubs code. Midl supports this and so it seems like a good idea for cppwinrt to expose it.
/cc @Scottj1s

Expose configuring /nomidl.

---

strings/base_activation.h
strings/base_agile_ref.h
strings/base_extern.h

This avoids DLL planting issues during the fallback search for a base trust server. It uses the `LOAD_LIBRARY_SEARCH_DEFAULT_DIRS` flag, which searches the usual places, including the application directory, but excludes the current directory. The flag is supported on Win8 onward, as well as on Win7 if you have KB2533623 installed (which you really should). If you need to support versions of Win7 that haven't been patched since 2011, then stick with whatever version of C++/WinRT you are currently using.

Use safe DLL loading (avoid current directory)

---

test/old_tests/UnitTests/clock.cpp
test/test_cpp20/custom_error.cpp

Clock test needs to take double-rounding of time_t into account.
Fix fragility in line-number test by using `#line` directive.

Fix flaky clock and line-number tests

---

.pipelines/OneBranch.Official.yml
.pipelines/OneBranch.PullRequest.yml
.pipelines/jobs/OneBranchBuild.yml
.pipelines/jobs/OneBranchNuGet.yml
.pipelines/jobs/OneBranchTest.yml
.pipelines/jobs/OneBranchVsix.yml
.pipelines/variables/OneBranchVariables.yml
.pipelines/variables/version.yml

This moves our official build pipelines to OneBranch.
There are actually two pipelines here: OneBranch.Official and OneBranch.PullRequest. The PullRequest pipeline is an option to run when sources are synced to a private mirror, just to validate that everything is still working, but without code signing and skipping other publishing steps for vpacks and nuget.
There are still some bizarre test failures when running the tests within the OneBranch containerized environment. I'll keep an action item on myself to run down the investigation on that (or mitigate it some other way), but we'll have lots of testing in our CI pipelines, so it's not an emergency right now.

Move official build pipelines to OneBranch

---

.pipelines/variables/OneBranchVariables.yml

Used to have a workaround in the OneBranch build to fix an ARM build break. That workaround is no longer neccessary, and is actually causing build difficulties now, so we should go back to using the default latest image.

Remove ARM build workaround

---

cppwinrt/app.manifest

This takes advantage of a Windows 10 manifest property to set the [process code page to UTF-8](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#set-a-process-code-page-to-utf-8).
Prior to this update:
```
cppwinrt.exe -in d:\Test❤️\Windows.winmd -out d:\Test❤️
cppwinrt : error Path 'd:\Test??\Windows.winmd' is not a file or directory
```
With this update:
```
D:\git\cppwinrt\_build\x86\Release\cppwinrt.exe -in d:\Test❤️\Windows.winmd -out d:\Test❤️
```
Input is parsed correctly and output is generated correctly.
I'm reluctant to add a test for this scenario to avoid complicating the build.
Fixes: #1306

Add UTF-8 path support

---

.github/workflows/ci.yml

Previously, the trigger would run the workflow for "each push and PR to master" when it should be for "each PR and push to master". This should significantly cut down on the resources needed for a workflow.

Fix workflow trigger

---

test/test_cpp20/custom_error.cpp

What's this all about?
Fix a test case failure caused by changing compiler behavior in a newer compiler version.  The signature that MSVC provides for source_location has changed recently.
Instead of chasing the full decorated name, with each compiler having a slight variation, we now match just the meaningful substring that we care about "FailOnLine15".  This should now be stable across compilers and across compiler versions.
Fixes: #1325

Fix cpp20 source location test failure resulting from newer compiler

---

cppwinrt/code_writers.h
strings/base_delegate.h
test/old_tests/UnitTests/delegate_weak_strong.cpp
test/test/variadic_delegate.cpp

Add support for registering event handlers with shared_ptr and weak_ptr

---

README.md
build_nuget.cmd
cppwinrt.sln
nuget/Microsoft.Windows.CppWinRT.nuspec
strings/base_delegate.h
strings/base_events.h
strings/base_implements.h

SizeBench revealed heavily non-foldability of certain C++/WinRT templates contributing to increased Windows binary sizes. Some small tweaks dropped the size of `test.exe` (release, x64) by ~132kb. (5180416 -> 5030400, or 2.8% ... which isn't a super lot, but it's nonzero.
Fixes #1334 and related
**Enable nuspec iteration** - Bump the default nuspec version to 3.0.0.0 so `build_nuget.cmd` and iterating with a local nuget source is easier.
**Add solution files** - Niceness for people who live in Visual Studio.
**Fold delegate bases** - Forced the layout of the delegate types to be regular by moving the reference count into a base _before_ the non-ABI types. This folds nearly all the AddRef/QueryInterface instances into one. Releases are still unique because they call up into dtors.
**Fold …

Increase foldability of various templates

---

.github/workflows/ci.yml
README.md
build_test_all.cmd
cppwinrt.sln
test/test_component/test_component.vcxproj

Added a custom build projection step to the `test_component.vcxproj` that consumes the just-built `cppwinrt.exe` for single-pass "build solution" dev inner loop.
The previous instructions said to build the cppwinrt.exe tool then run the build_projections.cmd. This way I can make a change to a base_foo.h strings file, hit "build solution", come back, and run tests directly.
I'm amenable to adding a specific new target that does projection into the root "targets" file. There's already build order dependencies between test components, so this isn't _too_ much worse, but it does mean that "test_component.vcxproj" becomes a bottleneck.  Could also have the cppwinrt project have a post-build step that does the projection, since all the test projects rely on it anyhow.
(Note that ARM64 and ARM …

Enable faster dev cycle in Visual Studio

---

strings/base_implements.h

This removes `constexpr` from the `template <typename D, bool>` implementation of `root_implements_composable_inner::outer()`.
This was causing `nonnull` warnings in GCC such as:
winrt/base.h: In instantiation of 'int32_t winrt::impl::root_implements<D, I>::GetIids(uint32_t*, winrt::guid**) [with D = py::python_iterable<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::hstring> >::iterator; I = {winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::hstring> >}; int32_t = int; uint32_t = unsigned int]':
winrt/base.h:8163:49:   required from 'winrt::impl::hresult_type winrt::implements<D, I>::GetIids(winrt::impl::count_type*, winrt::impl::guid_type**) [with D = …

drop constexpr from root_implements_composable_inner::outer()

---

strings/base_coroutine_foundation.h
strings/base_coroutine_threadpool.h
strings/base_meta.h
test/test/await_adapter.cpp

By default, `co_await`'ing a Windows Runtime asynchronous operation resumes in the same COM apartment. We provide a way to override this behavior and resume in any apartment by wrapping the asynchronous operation in `resume_agile()`.
```cpp
extern IAsyncAction Example();
// This resumes in the same apartment
co_await Example();
// This resumes in any apartment
co_await resume_agile(Example());
```
The guts of the change are in `disconnect_aware_handler` which accepts a `preserve_context` template parameter, defaulting to `true`. If `false`, then we bypass the `resume_apartment()` on completion. The `false` value is provided by the `resume_agile()` function.
To remove the `resume_apartment_context` from the `disconnect_aware_handler` in the case where we don't need it, I use EBO and make …

resume_agile to allow coroutine to resume in any apartment

---

strings/base_coroutine_foundation.h
test/test/await_adapter.cpp

`resume_agile` exposes the ability to save the `await_adapter` in a variable. This was not possible without `resume_agile` because the `await_adapter` had previously been available only via `operator co_await`, which means that it is created only in response to an immediate attempt to `co_await` it, so we knew that it would be consumed before its argument (possibly a temporary) was destructed.
`resume_agile` returns the `await_adapter`, and we expect people to await it immediately, but it's possible that they decide to save it in a variable and await it later. In that case, we have to record the `Async` as a value instead of a reference. We forward the `resume_agile` argument into the `Async` so that it moves if given an rvalue reference, or copies if given an lvalue reference. This …

Allow resume_agile to be stored in a variable

---

.github/actions/setup-llvm-msvc/action.yml
Directory.Build.Props
test/test_cpp20/custom_error.cpp

In #1372 it looks like the build VMs were updated to a more recent VS and VCRT and STL combination, requiring an updated LLVM toolchain. This bumps the target LLM version to match.

Update GitHub action LLVM version to 17.0.5

---

cppwinrt/code_writers.h
strings/base_delegate.h
test/old_tests/UnitTests/delegate_weak_strong.cpp

We have found that a very common pattern for event handlers is to capture a weak reference into a lambda, and in the event handler, try to upgrade the weak reference to a strong one, and if so, do some work:
```cpp
widget.Closed([weak = get_weak(), data](auto&& sender, auto&& args)
{
if (auto strongThis = weak.get())
{
strongThis->do_all_the_things(data);
}
});
```
This commit extends the existing delegate constructors to permit a `winrt::weak_ref` + lambda (or `std::weak_ptr` + lambda), which simplifies the above to
```cpp
widget.Closed({ get_weak(), [this, data](auto&& sender, auto&& args)
{
do_all_the_things(data);
} });
```
A lambda and pointer to member function are hard to distinguish in a template parameter list. In theory, we could use SFINAE or partial specialization, but a …

Allow delegates to be created with weak reference + lambda

---

.pipelines/build.yml

#1338 changed the NuGet version to a property, but didn't update the build.yml to do the same thing

Fix pipeline build error in NuGet

---

strings/base_error.h
test/test/suppress_error_info.cpp
test/test/test.vcxproj

Fail gracefully when error reporting is suppressed

---

nuget/Microsoft.Windows.CppWinRT.targets

The original attempt at a fix for this was too aggressive: https://github.com/microsoft/cppwinrt/pull/1381/files
This fix is targeted specifically at removing references to stale winmd files that have yet to be copied from referenced projects (e.g., from a runtime component to an app).

Remove references to stale winmd files to fix incremental builds

---

.github/actions/setup-llvm-mingw/action.yml
.github/actions/setup-llvm-msvc/action.yml

`actions/cache@v3` runs on node16 which is deprecated.
Unlike `actions/*-artifact@v4`, `actions/cache@v4` is a drop in upgrade:
https://github.com/actions/cache?tab=readme-ov-file#v4

Use `actions/cache@v4`

---

strings/base_collections_base.h

This matches the visibility of `observable_vector_base::call_changed` to enable derived classes to raise change notifications when the underlying container changes.
Fixes: #1422

Changed visibility of `observable_map_base::call_changed` to `protected`

---

strings/base_includes.h

Clang with `std=c++23` rightfully complains that `std::exception_ptr` isn't defined.

Add missing `<exception>` to base_includes.h

---

nuget.config

Adding NuGet.config with public feed that upstreams to NuGet.org per guidance.

Add NuGet config

---

.pipelines/build.yml
.pipelines/jobs/OneBranchBuild.yml
.pipelines/jobs/OneBranchTest.yml
.pipelines/jobs/OneBranchVsix.yml

Previous PR adding nuget.config wasn't enough as a couple nuget restore tasks still used nuget.org.  Updating the tasks to use the nuget.config.

Update NuGetCommand to use nuget.config

---

vsix/ItemTemplates/BlankPage/BlankPage.h
vsix/ItemTemplates/BlankUserControl/BlankUserControl.h
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/MainPage.h

The default template describes what *not* to do with `InitializeComponent`, but it doesn't describe how developers are supposed to interact with it. This change clarifies the comment so it's more obvious why the link is relevant to the developer.

Clarify how InitializeComponent works in the template comment

---

strings/base_collections_base.h
strings/base_collections_vector.h

Clang-tidy (and I'm pretty sure just Clang in general since this is a Clang diagnostic) warns that these variables are unused. This happens because the single threaded collections types use the following lock guard type:
```c++
struct nop_lock_guard {};
```
I could also fix this issue by adding a destructor to the type, however that may have consequences on code-gen. This seemed to be the less risky change with the tradeoff of touching more lines.

Silence clang-tidy "unused variable" warnings

---

cppwinrt/code_writers.h

Current codegen was triggering [Warning C24695 - Variable 'foo' is uninitialized](https://learn.microsoft.com/en-us/cpp/code-quality/c26495?view=msvc-170).
This adds a default initializer to struct fields.
Before:
```cpp
namespace winrt::Windows::UI::Xaml::Interop
{
struct TypeName
{
hstring Name;
winrt::Windows::UI::Xaml::Interop::TypeKind Kind;
};
}
```
After:
```cpp
namespace winrt::Windows::UI::Xaml::Interop
{
struct TypeName
{
hstring Name {};
winrt::Windows::UI::Xaml::Interop::TypeKind Kind {};
};
}
```
Since consume* methods that return a struct are already value-initializing the return value, this has a negligible effect on the compiler codegen there. So that's nice.

Value-init fields of WinRT structs (fix warning C24695 in generated code)

---

strings/base_error.h
strings/base_macros.h
strings/base_meta.h

Someone is trying to upgrade the cppwinrt version used by a large project that has many static libraries using cppwinrt.  Some binaries in that project are mixing static libs with different cpp language versions.  (This seems like not a great idea generally but it is the state of the world so to some degree we have to live with it).  In those binaries the ODR checks for cppwinrt source_location usage are breaking the build.  For good reason, it is not safe to mix this functionality across language versions.  This set of changes is aimed at making that upgrade process easier without losing any useful functionality.
We already have `winrt::impl::slim_source_location` which is a lot like `std::source_location`, minus always containing the very impactful FUNCTION data.  This type is powered …

WINRT_SOURCE_LOCATION has ODR checks that prevent mixing cpp17 and cpp20 static libraries

---

.pipelines/OneBranch.Official.yml

Trying to test the latest changes using a vpack, the latest vpacks are being built with an extra cppwinrt folder compared to previous vpacks. Unclear why this has changed, but it's been a long time since the last vpack was built, so any number of minor changes could have resulted in this.
Prior vPack contents:
```
|- cppwinrt.exe
|- cppwinrt.pdb
```
Latest vPack contents:
```
|- cppwinrt/
|- cppwinrt.exe
|- cppwinrt.pdb
```
This simply changes the vpack contents structure back to the prior format, to avoid needlessly churning the consuming build systems.

Latest vpack has an extra cppwinrt folder

---

cppwinrt/code_writers.h
strings/base_error.h

I have been doing some local builds of an internal component against the latest cppwinrt.exe, which includes the fixes in #1442.  I have noticed some modest (1%) binary size grown when comparing the April 2024 release and the latest.  Using SizeBench to analyze binary size differences I determined that the inlined code gen seems to explain the difference.  This change eliminates that increase, at least for the binary I'm testing against, and even shrinks it a bit further.
The various `winrt::impl::consume_THING` methods get heavily inlined in release builds.  The current code gen has some casts for when the types don't match (and is an AddRef/Release when they do match).  The small amount of new cast result checking ends up at many call sites and slowly adds up a bit.  I think we can do …

Reduce the code size of generated consume methods by skipping casts when the type is already a match

---

cppwinrt/code_writers.h
strings/base_error.h
strings/base_extern.h
strings/base_implements.h
strings/base_windows.h

I have been trying to ingest the HEAD of cppwinrt for some large internal projects and one of them had some test failures with the new version.  The failures are because there is a `try_as` cast in their code that fails and is handled fine, but it leaves a COM error context floating around on that thread.  Subsequent code fails to originate an error because it sees a context already active on the thread and NOOP'ed.
What this boils down to is that `try_as` should not have a behavioral change to store context when the cast fails.
To address this problem I am taking a PR suggestion from @oldnewthing to have a new `try_as_with_reason` method that returns both the cast result as well as the HRESULT.  The error context logic was only there to smuggle the HRESULT out of a call without an …

try_as casts should not store COM error context; consume method cast checking should use return codes directly

---

.github/workflows/ci.yml
test/nuget/ConsoleApplication1/ConsoleApplication1.vcxproj
test/nuget/ConsoleApplication1/packages.config
test/nuget/TestRuntimeComponentCSharp/TestRuntimeComponentCSharp.csproj
test/nuget/TestRuntimeComponentNamespaceUnderscore/packages.config
test/nuget/TestStaticLibrary7/TestStaticLibrary7.vcxproj
test/nuget/TestStaticLibrary7/packages.config
vsix/ProjectTemplates/VC/Windows Desktop/ConsoleApplication/ConsoleApplication.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/BlankApp/BlankApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/CoreApp/CoreApp.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/StaticLibrary/StaticLibrary.vcxproj
vsix/ProjectTemplates/VC/Windows Universal/WindowsRuntimeComponent/WindowsRuntimeComponent.vcxproj

These failures were pointed out yesterday when the CLA policy was stuck.  They are not blocking but have seemingly been failing for a long time and the failure is suppressed.
The issue seems to be that some of these test projects reference an old NuGet package while also referencing the props/targets that are about to go into the new NuGet package.  Double-including essentially the same files twice is what caused the build breaks in these projects.
Some projects also had build breaks that seem to be related to a very old Windows SDK minimum version.  I increased the floor to 10.0.18362.0 (early 2019; almost 6 years ago) and that fixed the remaining breaks.  The random packages.config that downloaded random builds of cppwinrt from 2019 or 2020 have been deleted too.
This set of changes …

Try to fix the disabled/failing nuget test build step

---

cppwinrt/code_writers.h

@DefaultRyan discovered a subtle compatibility issue with the cast result checking changes and certain projected methods.  The variables in the consume_ method, such as the generically-named `code` variable, can shadow the parameters to the function.  This led to a build break where a function took an int16_t named `code` and that was shadowed by the `int32_t` named `code` with the HRESULT in it.  Fortunately the compiler had our back and flagged the size truncation as a build break so it was noticed.
The variable names in these generated functions are now much uglier (and therefore less likely to collide by coincidence).  They have an underscore prefix and then lowercase which should put them into an unofficial namespace that shouldn't collide with anything else.  The `code` variable is …

The new variables in winrt::impl::consume_ methods can collide with parameters to that method

---

cppwinrt/code_writers.h
test/test_component/OverloadClass.cpp
test/test_component/OverloadClass.h
test/test_component/test_component.idl
test/test_component/test_component.vcxproj
test/test_component/test_overload.cpp

Fix overloads coming from overridable interfaces

---

cppwinrt/code_writers.h
strings/base_implements.h
strings/base_windows.h

The temporary std::pair introduced with `try_as_with_reason` sometimes causes spurious temporary dtor calls, depending on the optimization flags used and/or the version of the compiler. This didn't result in an extra refcount bump/release, but it still resulted in generating spurious destructor calls to `winrt::Foundation::~IUnknown()` as a result of that temporary.
The temporary had already been moved-from into the local variables, so was always zero, but this code bloat, extra function call and branch, when multiplied over thousands of projected methods can still add up.

Make consume methods more amenable to optimization

---

natvis/cppwinrt_visualizer.cpp
natvis/object_visualizer.cpp
natvis/pch.h

There are a slew of compilation warnings in the natvis project. This addresses them.
Most are coming from a the `<vsdebugeng.h>` header in the `Microsoft.VSSDK.Debugger.VSDebugEng.16.0.2012201-preview` package.
But there were a few where a global variable named `db` was getting hidden by a local `db` in a different scope. Let's just give the global a more unique name for now.

Fix warnings in natvis project

---

Directory.Build.Props
Directory.Build.Targets

Building cppwinrt was generating a bunch of warnings like 
```
(CreateRecipeFile target) ->
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(2566,5)
: warning : Remote deployment might be slow/inefficient. Could not find a part of the path 'E:\GitHub\cppwinrt\fast_fwd
\x64\Release\cppwinrt_fast_forwarder.lib.recipe'. [E:\GitHub\cppwinrt\fast_fwd\fast_fwd.vcxproj]
```
I tracked this down to us setting `IntDir` too late in Directory.Build.targets, which was too late, and processed after a bunch of other logic. The result of this was that `IntDir` got the default value, which was then used for `IntDirFullPath`, and then we overrode `IntDir`.
Some MSBuild *.Targets would then use the inconsistent `IntDirFullPath` and complain about …

Fix setting of IntDir MSBuild property

---

cppwinrt/component_writers.h
prebuild/prebuild.vcxproj
strings/base_composable.h
strings/base_implements.h
test/old_tests/Component/Component.idl
test/test/fast_iterator.cpp
test/test_component/OverloadClass.cpp
test/test_component_base/HierarchyB.cpp

Needed to fix a BinSkim issue flagging CFG on prebuild.exe. While I was at it, I fixed a few more warnings. A few were genuine code tweaks, a few were warning suppressions for stuff that's either by design or out of our control.
At this point, the official build pipelines are looking almost 100% clean. Might even be able to enable /WX and cause the build to break on new warnings.

Fix various build warnings

---

.github/workflows/ci.yml
test/old_tests/Component/Component.vcxproj
test/old_tests/Composable/Composable.vcxproj
test/test_component/test_component.vcxproj
test/test_component_base/test_component_base.vcxproj
test/test_component_derived/test_component_derived.vcxproj
test/test_component_fast/test_component_fast.vcxproj
test/test_component_folders/test_component_folders.vcxproj
test/test_component_no_pch/test_component_no_pch.vcxproj

Just use the one included in Visual Studio
CI runs have broken again because the hard-coded version of clang we manually download is now older than the version included in Visual Studio.
Given that the rationale at the time was apparently to test with a newer version than what was in VS, this strategy is now backfiring, as we are now testing with something *older* thatn what is in VS. Let's just use the inbox version going forward.
I'm fine with leaving that action yml around for now in case we change our minds, but we'll no longer call it.
Also of note: I found that somehow between the old clang and the new clang 19 that's included in VS, overriding ExecutablePath was causing clang-cl problems. I got as far as figuring out that with those overrides, the clang copy of `vadefs.h` stopped …

Stop manually downloading hardcoded version of llvm/clang.

---

.pipelines/OneBranch.Official.yml
.pipelines/OneBranch.PullRequest.yml
.pipelines/jobs/OneBranchBuild.yml
.pipelines/jobs/OneBranchNuGet.yml
.pipelines/jobs/OneBranchTest.yml
.pipelines/jobs/OneBranchVsix.yml
natvis/cppwinrtvisualizer.vcxproj

More compliance work, this time enabline prefast and the compiler warnings checker.
While I was here I also noticed that the visualizer was overriding SDL to disabled, so went ahead and removed that to allow the default "Enabled" value to prevail again.

Enable prefast and warnings checker in SDL

---

.pipelines/OneBranch.Official.yml
.pipelines/OneBranch.PullRequest.yml
.pipelines/variables/OneBranchVariables.yml

I found that after #1479 a left overline in the msbuild vpack copy was clobbering the compiler contents we had previously copied over. Didn't notice until I tried to use the new vpack and cppwinrt.exe was missing.
While we're at it, let's go ahead and update our pipeline container images from 2019 to the latest (and recommended) 2022 version.

Fix vpack clobbering and update to newer Windows container image

---

Directory.Packages.props
test/nuget/TestRuntimeComponentCSharp/TestRuntimeComponentCSharp.csproj
vsix/Dev16/vsix.Dev16.csproj
vsix/Dev17/vsix.Dev17.csproj

This pull request introduces the NuGet [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management) feature to streamline dependency management. Key benefits and changes include:
- **Centralized Version Management**: All NuGet package versions are now managed centrally in the `Directory.Packages.props` file. This ensures consistency across all projects in the repository.
- **Simplified Project Files**: The individual project files are simplified, as they no longer need to specify version numbers for NuGet packages. This change reduces duplication and the potential for version conflicts.
- **Ease of Updating Dependencies**: Updating a package version is now a matter of changing it in one place, making the process of keeping dependencies …

Enable NuGet Central Package Management

---

cppwinrt/code_writers.h
strings/base_abi.h
strings/base_delegate.h
strings/base_fast_forward.h
strings/base_macros.h

It may also be appropriate to use `__attribute__ ((visibility ("default")))` on GCC, though I haven't looked into it.
Fixes: #1481

Declare public LTO visibility for ABI type declarations

---

cppwinrt/code_writers.h

Fix a line that was indented too much in the generated code.
This is just fixes something odd I noticed while reading the generated code.
Before:
```cpp
int32_t __stdcall CreateInstanceWithOwner(void* owner, void* baseInterface, void** innerInterface, void** value) noexcept final try
{
if (innerInterface) *innerInterface = nullptr;
winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
clear_abi(value);
typename D::abi_guard guard(this->shim());
*value = detach_from<winrt::Windows::UI::Xaml::Automation::Peers::AppBarAutomationPeer>(this->shim().CreateInstanceWithOwner(*reinterpret_cast<winrt::Windows::UI::Xaml::Controls::AppBar const*>(&owner), *reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
if (innerInterface) …
```

fix indent in generated code
